### ISSUE TITLE
Enhancement: Multi User Environment (Preferably LDAP)

### ISSUE THREAD

**Issue by drtech981** [WeeJeWel/wg-easy#10]
Kudos for this awesome project !
I had been using Subspace prior to this, but I must the deployment for this is much simpler and the UI is more polished. 

However one feature I would like to request is Multi User Environment (preferably with LDAP). Subspace offers SSO with ADFS, however that is not implemented easily.

**Comment by WeeJeWel** [comment]
I suggest you place something in front of this that supports that. One tool, one job.

**Comment by drtech981** [comment]
Yes, but integrating multiple users within the app will allow each user to manage only their devices, not fiddle with others.

**Comment by WeeJeWel** [comment]
Very niche usecase, I don't think it's worth the effort and complexity.

**Comment by drtech981** [comment]
Maybe someone with the apt skills can volunteer to make a branch/PR and add LDAP Auth.

**Comment by drtech981** [comment]
@WeeJeWel  https://github.com/rapejim please reconsider this
