### ISSUE TITLE
Create custom environment variable for client subnet mask

### ISSUE THREAD

**Issue by benisai** [WeeJeWel/wg-easy#106]
Can somebody please create environmental variable for the client config interface address to have a custom mask? 
Using /24 doesn't work for me and it needs to be /32. So I want to somehow define it in the docker compose and have it auto populate to the client config files. :) 

Example:: 

[Interface]
PrivateKey = 0o
Address = 10.10.10.3/32
DNS = 1.1.1.1

**Comment by WeeJeWel** [comment]
This is not an issue, please create a discussion.

**Comment by benisai** [comment]
> This is not an issue, please create a discussion.

You are wrong. This is an issue please reopen and correct.
