### ISSUE TITLE
Changing the Default Interface

### ISSUE THREAD

**Issue by RyanSchuddinh** [WeeJeWel/wg-easy#113]
Hey there. 

So all config seems to be good, however when running docker-compose up, the service establishes, however the PostUP and PostDown being used point to eth0 by default, which does not match the interface of my server. 

Is there a way to change the interface being used by wg-easy for the purpose of ensuring traffic is forwarded to the correct interface? 

My current only roadblock to making this work.

**Comment by WeeJeWel** [comment]
`eth0` is the interface inside the docker container, so it shouldn't matter.
