### ISSUE TITLE
Update Container without losing vpn-users

### ISSUE THREAD

**Issue by fanta2go** [WeeJeWel/wg-easy#116]
Is it possible to update/recreate the wg-easy container about portainer without losing the created vpn-users?

Thank you :-)...

**Comment by WeeJeWel** [comment]
I know nothing about portainer, but just keep the generated files :)

**Comment by fanta2go** [comment]
> I know nothing about portainer, but just keep the generated files :)

Sure, but if i create a user, where are the generated files saved, on which folder?

Portainer is a really cool Web-GUI to manage all your Docker-Container easily. Would be cool if it would be possible to recreate the wg-easy container with the newest image without saving the generated user-files seperatly :-).

**Comment by WeeJeWel** [comment]
It's where you mount `/etc/wireguard/` as volume. The files are `wg0.json` and `wg0.conf`.
