### ISSUE TITLE
Misleading "any WireGuard client will have access to the Web UI"

### ISSUE THREAD

**Issue by bluepuma77** [WeeJeWel/wg-easy#119]
In the readme it states
```
By default, any WireGuard client will have access to the Web UI, unless you set a password
```
which sounds like the GUI is limited to known WireGuard clients only.

I am trying to set up a WireGuard jump-host to access dedicated servers. When using
```
docker-compose up --detach
```
on one of them the GUI is suddenly available publicly for everyone to access, which seems dangerous.

Therefore I recommend an update of the wording to something like 
```
By default, any client on the host network will have access to the Web UI, unless you set a password
```

**Comment by bluepuma77** [comment]
While editing the readme:
```
sudo apt-get install docker-compose
```
[does not necessarily install the latest version](https://github.com/WeeJeWel/wg-easy/issues/80), so this could just link to the [docker compose page](https://docs.docker.com/compose/install/).

**Comment by bluepuma77** [comment]
[Docker Hub readme](https://hub.docker.com/r/weejewel/wg-easy) is outdated, it is at least missing option `WG_PERSISTENT_KEEPALIVE`.

**Comment by WeeJeWel** [comment]
This is fixed now.
