### ISSUE TITLE
Enhancement: Edit Client Name

### ISSUE THREAD

**Issue by drtech981** [WeeJeWel/wg-easy#12]
There's no way to edit a client's name once you hit submit. Granted I can just delete and re-add the client, it would be easier if there was an option to edit the client name !

**Comment by mikekosulin** [comment]
Until then you can do that by changing it in the `wg0.json` and `wg0.conf` and restarting wg-easy container

**Comment by rapejim** [comment]
> Until then you can do that by changing it in the `wg0.json` and `wg0.conf` and restarting wg-easy container

If only want edit name, I edit only `wg0.json` and I restart wg-easy container.

**Comment by rapejim** [comment]
@drtech981 can you try the changes for edit name and/or last ip number of my pull request?

https://github.com/WeeJeWel/wg-easy/pull/38

You can try this changes using temporally the docker image of my fork `rapejim/wg-easy`.
(IMPORTANT: this imagen is only for testing this changes, probably I delete it if WeeJeWel finally approve and merge the PR 😅).

**Comment by drtech981** [comment]
@rapejim 
I tested it and it works absolutely well ! Waiting for the PR to be merged.

**Comment by drtech981** [comment]
@rapejim can you also add an option for multiple user profiles so that each person can login and change only his or her devices ?

**Comment by rapejim** [comment]
> @rapejim can you also add an option for multiple user profiles so that each person can login and change only his or her devices ?

This is a "mayor" update (imho), and maybe you must requested with a new issue, 😅

**Comment by drtech981** [comment]
@rapejim https://github.com/WeeJeWel/wg-easy/issues/10 I had opened this request but had it closed. 
Can you reopen the issue and work on it ?

Greatly counting towards your contribution !

**Comment by WeeJeWel** [comment]
I wonder what you want non-admin users to be able to do?

**Comment by drtech981** [comment]
Admin can choose to add local users (authelia/sso) / LDAP auth, and each user can add or remove their devices.

I use WG extensively to access my clinic's PBX,  and so do my colleagues. However a single page lists all devices, and many a times there's an accidental deletion or someone disables someone's else device. Would be great if one person is responsible for their set of devices only.

I know, a very niche case, but work on it would be great.

**Comment by rapejim** [comment]
> Admin can choose to add local users (authelia/sso) / LDAP auth, and each user can add or remove their devices.
> 
> I use WG extensively to access my clinic's PBX,  and so do my colleagues. However a single page lists all devices, and many a times there's an accidental deletion or someone disables someone's else device. Would be great if one person is responsible for their set of devices only.
> 
> I know, a very niche case, but work on it would be great.

I thinking that now you can deploy one wg-easy docker container for each user? 🤔

With diferents ports (and diferents subdomains with a reverse proxy) you can separate all, 😜

Because, your suggests it's not quick/easy, 😅 (imho)

**Comment by WeeJeWel** [comment]
Fixed :)

<img width="190" alt="Screenshot 2021-07-13 at 20 51 55" src="https://user-images.githubusercontent.com/319873/125508746-be6ac2e7-deac-43d1-9ffd-3777974568bf.png">

**Comment by WeeJeWel** [comment]
Consider donating: https://github.com/sponsors/WeeJeWel.
