### ISSUE TITLE
Helm Chart

### ISSUE THREAD

**Issue by brandon099** [WeeJeWel/wg-easy#126]
I wasn't sure where to post this, so hopefully this works.

I've created a [Helm Chart](https://github.com/brandon099/wg-easy-helm-chart) for deploying wg-easy to Kubernetes. It's something that can simply be moved into this project via PR (it does have some GitHub Actions to bundle the Helm Release and host it on gh-pages), or just link to it in this project's readme. I'm good either way and just thought I'd share, since I'm benefiting from this awesome project. 

Thanks!

**Comment by WeeJeWel** [comment]
OK Thx!
