### ISSUE TITLE
Specify client MTU size as environment variable? (Android OK, Windows broken)

### ISSUE THREAD

**Issue by fightforlife** [WeeJeWel/wg-easy#127]
I tried multiple days to get this this working. On Android client this worked fine from the first second.
But on Windows client the routing did never work. 

After a lot of googling I found the following entry, which solved all my problems with the window client immediately:
https://superuser.com/questions/1649755/wireguard-windows-client-not-working-while-android-is-ok

In short: the correct MTU size has to be set on the windows client side. e.g. MTU = 1280 from Android.
`60 (IPv4) / 80 (IPv6) bytes less than the MTU of the Ethernet interface on the same host`

Maybe it would be possible to include this info on this github page? So other users find it quickly.
Or even include this as an optional Environment variable for the generated config file?

Thanks in advance! I love this image!

**Comment by DerDanilo** [comment]
https://github.com/WeeJeWel/wg-easy/issues/95

Just commited a feature to add a custom MTU into client profiles. This way one can at least configure this in the clients profiles.

**Comment by WeeJeWel** [comment]
Fixed. Now the `nightly` tag is available for every automatic build, and for the latest manual-built, pull `latest`.

[Consider donating! 🍻](https://github.com/sponsors/WeeJeWel)
