### ISSUE TITLE
How to change DNS to ufollows host's?

### ISSUE THREAD

**Issue by astronyu** [WeeJeWel/wg-easy#128]
My network is running through pihole and instead of the default 1.1.1.1, how can I set this script so that it would follows host's DNS?

Also, what is the default WG server address?

**Comment by Zauberio** [comment]
same issue here

**Comment by Zauberio** [comment]
So I fixed it manually by going to each client and replacing the DNS Server with my Pi-hole IP and the Endpoint with thr Pi-hole IP:51820
