### ISSUE TITLE
Connecting issue on windows

### ISSUE THREAD

**Issue by sadequzv710** [WeeJeWel/wg-easy#129]
Hello.✌
I am using docker on my Linux server. everything works fine.
I can connect on my mobile phone without problem ( android 10 and 11 tested ) 
but it doesn't connect on windows. I don't know why.( windows 10 & official app from wireguard site )

thanks.🙌

**Comment by pelijaro** [comment]
Hello,

I have a similar problem and sometimes it doesn't connect for the following reason:  

But it is a random problem which sometimes works again when I retry to connect several times, sometimes when I disable the wifi adapter. The strange thing is that I have several Win10 devices with the client installed and running smoothly, also on Andrioid running smoothly.

The other day I accessed the IRC channel of the creators of the app but got no response.

![image](https://user-images.githubusercontent.com/11003546/143030493-db07b481-be22-482c-adcc-847ab7f4b85b.png)

**Comment by DavideVairetti** [comment]
Installed a few days ago and I have the same problem. I can connect with my Android phone without a problem but when I try on Windows 10/11 machines I have no internet access.
Do you find a solution?
