### ISSUE TITLE
New Update Issue 

### ISSUE THREAD

**Issue by MANKUD** [WeeJeWel/wg-easy#132]
Hello,

After the new update now instead of the bandwidth utilized it's showing the client's network speed. It would be great if it would show both the client connection speed and the bandwidth  (data) used. 

![image](https://user-images.githubusercontent.com/83474708/143285780-c65a934b-8796-421b-9190-b6dadf2a6681.png)

![image](https://user-images.githubusercontent.com/83474708/143285873-09659369-a6f0-472b-83d9-0a57894d4a37.png)

**Comment by rahulhaque** [comment]
I am wondering the same. Previously it used to show consumed traffic. Now it's gone.

**Comment by WeeJeWel** [comment]
I'll add it as a title attribute asap

**Comment by MANKUD** [comment]
> I'll add it as a title attribute asap

That you would be great thank you :)

**Comment by WeeJeWel** [comment]
Fixed in https://github.com/WeeJeWel/wg-easy/commit/1b036c3b4cdb84790937bc087dc274a023fbc93d !

Please consider [buying me a beer! 🍻](https://github.com/sponsors/WeeJeWel)
