### ISSUE TITLE
WG_PORT not working

### ISSUE THREAD

**Issue by mahanxdev** [WeeJeWel/wg-easy#133]
Hi.
I want to change the default udp port but it just keep on default and doesnt change!

**Comment by Schrolli91** [comment]
Internal Port is always 51820.
You have to change the port mapping from docker command to map your port to the internal
eg. `55055:51820/udp`

'WG_PORT' is only the value which is added into the peer configs

**Comment by mahanxdev** [comment]
> Internal Port is always 51820. You have to change the port mapping from docker command to map your port to the internal eg. `55055:51820/udp`
> 
> `WG_PORT` is only the value which is added into the peer configs

yes. thank you!
