### ISSUE TITLE
OpenID support (or SAML)

### ISSUE THREAD

**Issue by fnpanic** [WeeJeWel/wg-easy#134]
It would be great to have an a way to auth to an existing auth source with OpenID or SAML.

keycloak-js can do it (https://www.keycloak.org/securing-apps/vue is a complete walk-through), or even https://www.npmjs.com/package/vue-oidc-client as a more generic one. There's also https://github.com/openid/AppAuth-JS

I'm not fluent enough in Vue, but I can do the tests for you on a dedicated branch if you are interested.

Another way would be to make auth optional and use oauth2-proxy https://github.com/oauth2-proxy/oauth2-proxy which works very well for other applications.

**Comment by WeeJeWel** [comment]
Sound to me like you wanna put an nginx container in front of it, configured with Vouch or oauth2-proxy.

Remember: one tool, one job!
