### ISSUE TITLE
sh get-docker.sh sh: 0: Can't open get-docker.sh

### ISSUE THREAD

**Issue by emiksTT** [WeeJeWel/wg-easy#135]
Hi, the first command works fine.
next one:

root@f679:~# sudo sh get-docker.sh
sh: 0: Can't open get-docker.sh

could someone help

**Comment by atdavewatts** [comment]
The readme has been updated to removed this command - check the newest version on master

https://github.com/WeeJeWel/wg-easy/blob/master/README.md

**Comment by qwasson** [comment]
The readme has been updated to removed this command - check the newest version on master

https://github.com/WeeJeWel/wg-easy/blob/master/README.md
