### ISSUE TITLE
error on container start

### ISSUE THREAD

**Issue by gpopesc** [WeeJeWel/wg-easy#137]
Hello

I am using Synology NAS DS218+ with docker version 20.10.3 and I get the bellow error.
I have another [winguard server ](https://github.com/masipcat/wireguard-go-docker) which is working, but there is not GUI on that server.
Any ideas how can I solve it with your build?

```
2021-12-04T15:12:56.815Z Server Listening on http://0.0.0.0:51821
2021-12-04T15:12:56.817Z WireGuard Loading configuration...
2021-12-04T15:12:56.820Z WireGuard Configuration loaded.
2021-12-04T15:12:56.820Z WireGuard Saving config...
2021-12-04T15:12:56.823Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: Command failed: wg-quick up wg0
Warning: `/etc/wireguard/wg0.conf' is world accessible
[#] ip link add wg0 type wireguard
RTNETLINK answers: Not supported
Unable to access interface: Protocol not supported
[#] ip link delete dev wg0
Cannot find device "wg0"
    at ChildProcess.exithandler (child_process.js:383:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'wg-quick up wg0'
}
```

My docker compose file is following:
```
version: "3.8"
services:
  wg-easy:
    environment:
      # Required:
      # Change this to your host's public address
      - WG_HOST=mydomain.com
      # Optional:
      - PASSWORD=mypass
      # - WG_PORT=51820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      # - WG_DEFAULT_DNS=1.1.1.1
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      
    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - ./conf:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

```
Thank you
Gabriel

**Comment by SmartPhoneLover** [comment]
Did you solve it? I'm facing the same problem during container start.

**Comment by schtinkafinga** [comment]
Having the same issue here.


![image](https://user-images.githubusercontent.com/63101257/148216040-239e1931-53ab-411f-bdd9-71e9ae356b12.png)

**Comment by niem94** [comment]
Same issue here. 

```docker
version: "3.8"
services:
  wg-easy:
    image: weejewel/wg-easy
    environment:
      - WG_HOST=mydomain.com
      - PASSWORD=/run/secrets/wireguard_password
    volumes:
      - wireguard_etc_wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    secrets:
      - wireguard_password
volumes:
  wireguard_etc_wireguard:
secrets:
  wireguard_password:
    external: true
```

```
2022-01-11T01:01:31.568Z Server Listening on http://0.0.0.0:51821,
2022-01-11T01:01:31.572Z WireGuard Loading configuration...,
$ wg genkey,
$ echo ***hidden*** | wg pubkey,
2022-01-11T01:01:31.615Z WireGuard Configuration generated.,
2022-01-11T01:01:31.616Z WireGuard Saving config...,
2022-01-11T01:01:31.621Z WireGuard Config saved.,
$ wg-quick down wg0,
$ wg-quick up wg0,
Error: Command failed: wg-quick up wg0,
[#] ip link add wg0 type wireguard,
RTNETLINK answers: Operation not permitted,
Unable to access interface: Operation not permitted,
[#] ip link delete dev wg0,
Cannot find device "wg0",
,
    at ChildProcess.exithandler (child_process.js:383:12),
    at ChildProcess.emit (events.js:400:28),
    at maybeClose (internal/child_process.js:1058:16),
    at Socket.<anonymous> (internal/child_process.js:443:11),
    at Socket.emit (events.js:400:28),
    at Pipe.<anonymous> (net.js:686:12) {,
  killed: false,,
  code: 1,,
  signal: null,,
  cmd: 'wg-quick up wg0',
}
```

**Comment by WeeJeWel** [comment]
This usually means that your host's kernel does not support WireGuard.

I've added this as an error message in https://github.com/WeeJeWel/wg-easy/commit/2a9a7eecac73d0a97672356f87a79a182acff356.

**Comment by niem94** [comment]
@WeeJeWel It does not happen with the linuxserver/wireguard image, which works fine on raspbian, so I am not sure if this is the case.

**Comment by WeeJeWel** [comment]
Does the 'official' run command work for you?

```
docker run -d \
  --name=wg-easy \
  -e WG_HOST=🚨YOUR_SERVER_IP \
  -e PASSWORD=🚨YOUR_ADMIN_PASSWORD \
  -v ~/.wg-easy:/etc/wireguard \
  -p 51820:51820/udp \
  -p 51821:51821/tcp \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --restart unless-stopped \
  weejewel/wg-easy
```

**Comment by gpopesc** [comment]
in my case, it didn't work, I get the same error

**Comment by niem94** [comment]
It works for me.

But I would really like it to work with docker-compose if possible.

**Comment by niem94** [comment]
The issue is related to Portainer. It works well if I do `docker stack -c docker-compose.wireguard.yml` on the master node with the above compose file I posted.

Portainer disallows access to the host by default, so I'm pretty certain that `/lib/modules:/lib/modules` aka the kernel modules are never loaded when deployed in Portainer. This might be related to Portainer not having capabilities support yet and is hopefully solved when it gets that <https://github.com/portainer/portainer/issues/4684>.
I will play around with it a little to see if I can find a workaround and share it here if I do. Otherwise, the solution to my problem was to deploy `wg-easy` manually with my aforementioned compose file and `docker stack -c docker-compose.wireguard.yml` on one of your master nodes. This way you are still able to see and monitor the stack in Portainer, but you won't be able to manage it completely until a solution to deploy it in Portainer has been found.

Sorry for any confusion, and thanks for this tool. It is super helpful! 🥳

**Comment by devantler** [comment]
> 
> 
> 
> 
> 
> 
> 
> 
> > The issue is related to Portainer. It works well if I do `docker stack -c docker-compose.wireguard.yml` on the master node with the above compose file I posted.
> 
> > 
> 
> > Portainer disallows access to the host by default, so I'm pretty certain that `/lib/modules:/lib/modules` aka the kernel modules are never loaded when deployed in Portainer. This might be related to Portainer not having capabilities support yet and is hopefully solved when it gets that [portainer/portainer#4684](https://github.com/portainer/portainer/issues/4684). I will play around with it a little to see if I can find a workaround and share it here if I do. Otherwise, the solution to my problem was to deploy `wg-easy` manually with my aforementioned compose file and `docker stack -c docker-compose.wireguard.yml` on one of your master nodes. This way you are still able to see and monitor the stack in Portainer, but you won't be able to manage it completely until a solution to deploy it in Portainer has been found.
> 
> > 
> 
> > Sorry for any confusion, and thanks for this tool. It is super helpful! 🥳
> 
> > 
> 
> > EDIT: Here is a workaround thanks to @fopina
> 
> > 
> 
> > ```
> 
> > version: '3.8'
> 
> > 
> 
> > services:
> 
> >   monitor:
> 
> >     image: fopina/portainer-capability-manager:0.1.1
> 
> >     volumes:
> 
> >       - /var/run/docker.sock:/var/run/docker.sock
> 
> >     deploy:
> 
> >       mode: replicated
> 
> >       replicas: 1
> 
> >       placement:
> 
> >         constraints: [node.role == manager]
> 
> > ```
> 
> > 
> 
> > ```
> 
> > version: "3.8"
> 
> > services:
> 
> >   wg-easy:
> 
> >     image: weejewel/wg-easy
> 
> >     environment:
> 
> >       - WG_HOST=domain.com
> 
> >       - PASSWORD=password
> 
> >       # - WG_DEFAULT_DNS=1.1.1.1
> 
> >     volumes:
> 
> >       - wireguard_etc_wireguard:/etc/wireguard
> 
> >     ports:
> 
> >       - "51820:51820/udp"
> 
> >       - "51821:51821/tcp"
> 
> >     cap_add:
> 
> >       - NET_ADMIN
> 
> >       - SYS_MODULE
> 
> >     sysctls:
> 
> >       - net.ipv4.ip_forward=1
> 
> >       - net.ipv4.conf.all.src_valid_mark=1
> 
> >     deploy:
> 
> >       labels:
> 
> >         io.portainerhack.cap_add: NET_ADMIN,SYS_MODULE
> 
> >       mode: replicated
> 
> >       replicas: 1
> 
> > volumes:
> 
> >   wireguard_etc_wireguard:
> 
> > ```
> 
> 
> 
> what would have to be changed to this workaround to work in a non swarm portainer?

Are you deploying the service with a docker-compose file?

**Comment by yllekz** [comment]
Hi folks...I'm confused, I have a Synology DS218+ with this same issue. I do not have Portainer deployed on this at all, but still get the same original issue. I see this issue is "closed" but I see no actual resolution. Can someone explain again what the fix was? I'm having trouble following the logic above. Was the fix that one needs to mount ``/lib/modules``?

**Comment by gpopesc** [comment]
For synology is not working this version. I tried a lot setup options, but none is working
try wireguard version from my first post here.

**Comment by yllekz** [comment]
I got it working. Bit of a pain to do so and is a REALLY hackey solution and I'm not super proud of it, but I did get it functional to the point where it doesn't just immediately vomit upon container start:

Basically you first install [runfalk/synology-wireguard](https://github.com/runfalk/synology-wireguard), make a throwaway config (it's not going to matter in a hot moment, stay tuned below) and setup per [this guide](https://mikkel.hoegh.org/2019/11/01/home-vpn-server-wireguard/). Then, I ran ``sudo wg-quick up wg0`` to actually stand up a wg0 interface which resolves the original error wg-easy was throwing regarding being unable to find a wg0 interface.

Now here's the hackey bit:

In my wg-easy docker-compose I volume mapped ``/etc/wireguard`` to ``/etc/wireguard`` which upon container start commanders the previous config file you temporarily configured per the first guide above. I could then get into the web interface, make a config, and the rest is standard.

Again, I'm not proud of this and I don't think it's super stable, but it did get me past this issue.

**Comment by frezeen** [comment]
no solution yet for this? impossible to install wg-easy on a synology docker?

**Comment by gpopesc** [comment]
nope for me. use the solution from my first post with another build

**Comment by jbsilva** [comment]
I got it working after installing the modules from https://github.com/runfalk/synology-wireguard

**Comment by gpopesc** [comment]
The packages are for DSM 6.x from 2020
Are they compatible with DSM 7.x?

**Comment by gpopesc** [comment]
I made a small script to install only wireguard module in Synology and afterwards the installation of wg-easy is straight forward.
https://github.com/gpopesc/wireguard-module-synology/

thank you @jbsilva for the idea.

**Comment by drewdiver** [comment]
> I made a small script to install only wireguard module in Synology and afterwards the installation of wg-easy is straight forward. https://github.com/gpopesc/wireguard-module-synology/
> 
> thank you @jbsilva for the idea.

Thank you!! 🙏 🤘 🙏
