### ISSUE TITLE
wg0.conf is world accessible

### ISSUE THREAD

**Issue by Tyfosho** [WeeJeWel/wg-easy#141]
Whenever I take down the wg0 interface, I get a warning that "wg0 is world accessible". It looks like the recommendation online is to change the permissions of wg0.conf to 600, but I'm not sure that can be done with automating the config with JSON. Is that something that needs to be addressed?

**Comment by WeeJeWel** [comment]
Fixed in #0d908f56a0d50a292a72f5f8077ae89692a42d73.

[Consider donating! 🍻](https://github.com/sponsors/WeeJeWel)
