### ISSUE TITLE
Updating while no update available

### ISSUE THREAD

**Issue by loranger** [WeeJeWel/wg-easy#148]
Hello,

Because of the [automatic docker builds](https://github.com/WeeJeWel/wg-easy/discussions/144), there is a new update every day.
You can process an [wg-easy update](/WeeJeWel/wg-easy#updating) every day if you wish. And every day, you will pull a brand new docker image, which is in fact the same as the day before, except the hash is different, so docker consider it's a new one.

It would be much convenient to provide an image only if there is a real release instead of automatically building a new image every day. Maybe the `latest` tag image could still use this automatic nightly build setup, but please do not include the versionned images. 
That's precisely the aim of the git and docker tags : Freezing a release and provide a universal consistent bundle, easily shareable and indentifyable.

For example, what is the new features/fixes included in `wg-easy:4@41fbed164ac8` ? 
What differences with yesterday's hash `7684976dfc91`, sunday's `fdd7557a1ccf`, and so on ?

**Comment by Shadow27374** [comment]
That would be nice yes.

**Comment by 1RandomDev** [comment]
Yes pls create an image that only updates if there's something new. I get an update notification every day although there's no new content.

**Comment by whatdemocracy** [comment]
I agree too.

**Comment by loranger** [comment]
Since I opened the issue, I upgraded my wg-easy image to

- `weejewel/wg-easy:4 7f935962c3ea`
- `weejewel/wg-easy:4 239d98ad9983`
- `weejewel/wg-easy:4 0e0774815e9e`
- `weejewel/wg-easy:4 76cfd20ef32d`
- `weejewel/wg-easy:4 01956abb3d07`
- `weejewel/wg-easy:4 3f0e11d61409`
- `weejewel/wg-easy:4 1f5551469b30`
- `weejewel/wg-easy:4 5716db44a409`
- `weejewel/wg-easy:4 3611dd579787`
- `weejewel/wg-easy:4 c97b0cb9cc0e` (Happy new year ! 🎉 )
- `weejewel/wg-easy:4 3304be3f9993`
- `weejewel/wg-easy:4 c8918d367b95`
- `weejewel/wg-easy:4 3cb1355c346e`
- `weejewel/wg-easy:4 4e6bd0f461d0`
- `weejewel/wg-easy:4 07419592e539`

I really feel up-to-date.

@WeeJeWel could you please remove automatic build for major releases ?

**Comment by WeeJeWel** [comment]
Fixed. Now the `nightly` tag is available for every automatic build, and for the latest manual-built, pull `latest`.

[Consider donating! 🍻](https://github.com/sponsors/WeeJeWel)
