### ISSUE TITLE
additional tags on Docker Hub of prior releases

### ISSUE THREAD

**Issue by benisai** [WeeJeWel/wg-easy#157]
Can we get additional tags on docker hub of prior releases. The new release is acting up, VPS cannot talk to Home server, logs are no help. Only change is the update to wg-easy updated16hrs ago.

**Comment by WeeJeWel** [comment]
Fixed. Now the `nightly` tag is available for every automatic build, and for the latest manual-built, pull `latest`.

[Consider donating! 🍻](https://github.com/sponsors/WeeJeWel)
