### ISSUE TITLE
GUI not working since 3.jan.2022

### ISSUE THREAD

**Issue by morvy** [WeeJeWel/wg-easy#159]
Hi,
I was trying to access the GUI but it's not responding. I have a watchtower with auto prune of old images so I don't have old working image. GUI was working 2 days ago, not it fails with the following message (wg-easy running on RPi3B):

```
[nodemon] starting `node server.js`
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::51821
    at Server.setupListenHandle [as _listen2] (net.js:1331:16)
    at listenInCluster (net.js:1379:12)
    at Server.listen (net.js:1465:7)
    at Function.listen (/node_modules/express/lib/application.js:618:24)
    at new Server (/app/lib/Server.js:134:8)
    at Object.<anonymous> (/app/services/Server.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1358:8)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 51821
}
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by bluepuma77** [comment]
Maybe check with `sudo netstat -tulpen` or similar which process is using the port already.

**Comment by morvy** [comment]
some magic happened overnight, today's build is working again. I have no other apps on that particular Pi so port conflict (without me touching it for 2 months) is highly unlikely

**Comment by bluepuma77** [comment]
Well, the error states EADDRINUSE which means a port conflict.  Please close your issue if it's working now.

**Comment by morvy** [comment]
If you don't mind, I found out it's not working directly on IP address, but if I use a hostname it works fine. Any idea why?
Below is the output from netstat

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name
tcp        0      0 0.0.0.0:51821           0.0.0.0:*               LISTEN      0          817897     32757/docker-proxy
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      0          15958      532/sshd
tcp        0      0 0.0.0.0:9000            0.0.0.0:*               LISTEN      0          20481      1071/docker-proxy
tcp6       0      0 :::51821                :::*                    LISTEN      0          819519     32765/docker-proxy
tcp6       0      0 :::22                   :::*                    LISTEN      0          15960      532/sshd
tcp6       0      0 :::9000                 :::*                    LISTEN      0          20486      1079/docker-proxy
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           108        7974       339/avahi-daemon: r
udp        0      0 0.0.0.0:51587           0.0.0.0:*                           108        7976       339/avahi-daemon: r
udp        0      0 0.0.0.0:68              0.0.0.0:*                           0          12646      518/dhcpcd
udp        0      0 0.0.0.0:51820           0.0.0.0:*                           0          818805     310/docker-proxy
udp6       0      0 :::5353                 :::*                                108        7975       339/avahi-daemon: r
udp6       0      0 :::58327                :::*                                108        7977       339/avahi-daemon: r
udp6       0      0 :::546                  :::*                                0          8018       518/dhcpcd
udp6       0      0 :::51820                :::*                                0          819524     318/docker-proxy

**Comment by WeeJeWel** [comment]
Seems to be unrelated.
