### ISSUE TITLE
No data connection

### ISSUE THREAD

**Issue by ItzYanick** [WeeJeWel/wg-easy#16]
Okay another Issue. So now that the server is up and running I created a client and added it from my phone. I switched from my phone from WiFi to LTE and turned on the VPN. It shows that it connected and in the webinterface I do see that it is connected but for some reason i cannot exchange any data. I am not able to access any webpage or if I try to access my internal Smart Home (which connects via a internal IP) it is not able to connect to it.
I changed the Default Address to 10.10.66.x because my subnet is 255.255.0.0 and all of my IPs are based on 10.10.x.x. I did saw that the CIDR was set to /24 in the client and i changed it to /16 but it did not helped at all. Maybe anyone got a solution.

**Comment by triagony** [comment]
I have the exact same issue. WG on my android phone shows a connection as well as the web interface. I only changed the dns to my "private" dns 10.0.0.2 in my lan - everything else is "standard" setting. Changing dns to 1.1.1.1 (or anything else) does not make a difference. 

kind regards

**Comment by triagony** [comment]
Found a solution for me: 

I added

`net.ipv4.ip_forward=1`

under

` sysctls:`
      `- net.ipv4.conf.all.src_valid_mark=1`

in the docker-compose.yml so that it looks like this: 

` sysctls:`
      `- net.ipv4.conf.all.src_valid_mark=1`
      `- net.ipv4.ip_forward=1`

That solved my connection issues.  

Kind regards.

**Comment by ItzYanick** [comment]
I can confirm that it fixed my issue! Closing the issue then. Thanks @triagony for helping!

**Comment by WeeJeWel** [comment]
Thanks, I've added this line to the repo. Should help others as well!
