### ISSUE TITLE
Clients are diplayed as connected for 10 minutes after disconnect

### ISSUE THREAD

**Issue by Bouni** [WeeJeWel/wg-easy#164]
I tested wg-easy and its the best wireguard UI I've used so far, good work 👍🏽 

Is it by intention that the clients are shown as connected for 10 more minutes after they've disconnected?

![image](https://user-images.githubusercontent.com/948965/148895668-8b3a2b44-0ef3-4832-bc52-db8e8bc40f11.png)

The upper client whent grey after 10 minutes after I've disconnetced, the lower still shows connected but is also disconnected.

**Comment by WeeJeWel** [comment]
Yes, there's no real way of knowing when someone disconnected, so there's a timeout.
