### ISSUE TITLE
Problem with the WG_Port Variable

### ISSUE THREAD

**Issue by Wolf6660** [WeeJeWel/wg-easy#171]
I have a problem with the WG_Port variable. That won't change

here my dockerconfig:

sudo docker run -d \
  --name=wireguadweb \
  --net net \
  --ip 192.168.0.9 \
  -e WG_HOST=wolf.kopf-edv.de \
  -e WG_PORT=12345 \
  -e PASSWORD=test \
  -v ~/.wg-easy:/etc/wireguard \
  -p 12345:12345/udp \
  -p 51821:51821/tcp \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --restart unless-stopped \
  weejewel/wg-easy

Can you tell me what I'm doing wrong 

thanks

**Comment by WeeJeWel** [comment]
Change `-p 12345:12345/udp` to `-p 12345:51820/udp`.

**Comment by Wolf6660** [comment]
Thanks for the answer

I've tested it, but it doesn't work.

My to-do list:
1. open port 12345 UDP to my RPI-WG-Easy server on my router
2. My configuration:
   sudo docker run -d \
    --name = wireguadweb \
    --net net \
    --ip 192.168.0.9 \
    -e WG_HOST = test.bla.de \
    -e WG_PORT = 12345 \
    -e PASSWORD = lonsdaple \
    -v ~ / .wg-easy: / etc / wireguard \
    -p 12345: 51820 / udp \
    -p 51821: 51821 / tcp \
    --cap-add = NET_ADMIN \
    --cap-add = SYS_MODULE \
    --sysctl = "net.ipv4.conf.all.src_valid_mark = 1" \
    --sysctl = "net.ipv4.ip_forward = 1" \
    --restart except-stopped \
    Jewel / wg-easy

Error Handshake was not completed

**Comment by WeeJeWel** [comment]
Should work. Make sure your client downloads the config _after_ changing the port.

**Comment by Wolf6660** [comment]
I deleted the Docker container and the .wg_easy folder in /home/pi

and then i reinstalled it

**Comment by Wolf6660** [comment]
the config in my mobile phone is the correct port and DynDNS

**Comment by a-wenzel** [comment]
open the client.conf file and look at the IP in it... i changed the docker-udp-port and the generated file still have 51820 in the client.conf

Changed it manual and it works
