### ISSUE TITLE
Currently PreUp/PreDown not available

### ISSUE THREAD

**Issue by dermute** [WeeJeWel/wg-easy#176]
Hey,
I read in the Issues that you recently added WG_POST_DOWN  and WG_POST_UP.

For my configuration I would like to enable all clients to access the internet (safe surfing through home from a remote destination/public wifi). In order to make that possible the following rules are needed in the servers configuration.
PreUp = iptables -t nat -A POSTROUTING -j MASQUERADE -o eth0
PreDown = iptables -t nat -D POSTROUTING -j MASQUERADE -o eth0

Can you add similar variables for WG_PRE_DOWN and WG_PRE_UP?

Thanks.

**Comment by WeeJeWel** [comment]
Sure, create a PR. Shouldn't be hard.

**Comment by antoniomolram** [comment]
I was also searching for this feature. +1
