### ISSUE TITLE
The default HTTP access port is 51821. Can I change it to HTTPS

### ISSUE THREAD

**Issue by chenxudong2020** [WeeJeWel/wg-easy#183]
The default HTTP access port is 51821. Can I change it to HTTPS

Or it does not support HTTPS to use custom certificates

**Comment by Teraskull** [comment]
You should use Caddy for that, for example.

**Comment by ApexioDaCoder** [comment]
On my server, I am using an Nginx reverse proxy and certbot.

**Comment by chenxudong2020** [comment]
直接修改源码 启动nodejs内置https服务器 同时修改为中文支持

Directly modify the source code, start nodejs built-in HTTPS server, and modify it to Chinese support

https://gitee.com/opopop880/wg-easy.git

![1643179742(1)](https://user-images.githubusercontent.com/61214170/151116324-d440f117-4ff1-4478-ad34-5372b495da70.png)

**Comment by chenxudong2020** [comment]
> You should use Caddy for that, for example.

https://gitee.com/opopop880/wg-easy.git

**Comment by chenxudong2020** [comment]
> On my server, I am using an Nginx reverse proxy and certbot.

https://gitee.com/opopop880/wg-easy.git

**Comment by Teraskull** [comment]
> Directly modify the source code, start nodejs built-in HTTPS server, and modify it to Chinese support

That's bad practice, but whatever. Why not just use secure established software like Nginx for this purpose?
