### ISSUE TITLE
High CPU usage with Firefox

### ISSUE THREAD

**Issue by inclementweather** [WeeJeWel/wg-easy#187]
Hello, I just set this up and I have added 12 client configs from the interface.  If I leave the tab open it causes high CPU usage and it seems to get worse the longer its open.  No clients need to be connected.

**Comment by mikekosulin** [comment]
Didn't check yet, but seems like this issue caused by [adding charts](https://github.com/WeeJeWel/wg-easy/commit/7cd677f7ef2fe20e4a2d22e146b1df6ade08878c).

I think, it's good to have an option to disable charts

**Comment by WeeJeWel** [comment]
I'd like to know why this CPU is so high, it shouldn't happen, those charts are easy to render.

**Comment by mikekosulin** [comment]
Microsoft Edge (96.0.1054.57)
MacOS 12.1 on MacBook Pro 16" 2019

![image](https://user-images.githubusercontent.com/6089872/158190938-0c652b71-e5fe-4e94-a82d-77b002542e80.png)

p.s. the chart dropped on a page reload.

**Comment by inclementweather** [comment]
Same high load just on apexchart's realtime demo page although not as bad, but i'm assuming that has to do with the number of charts on the page (12 on mine vs 4 on theirs).

https://apexcharts.com/javascript-chart-demos/dashboards/realtime/

Even in Chrome with only that page loaded i see ~35% cpu spikes when it refreshes.

**Comment by WeeJeWel** [comment]
Fixed

**Comment by mikekosulin** [comment]
<img width="1475" alt="image" src="https://user-images.githubusercontent.com/6089872/174294918-4dd05aeb-ac3d-4cec-8baf-aa9c2968a9eb.png">

better, but the same experience on 6-nightly and latest.
