### ISSUE TITLE
Allow setting default 'AllowedIPs ' for clients

### ISSUE THREAD

**Issue by zmiguel** [WeeJeWel/wg-easy#19]
I would like to request the ability to configure the 'AllowedIPs ' setting on the client downloadable file.

While having 0.0.0.0/0 and ::/0 works great if you want a VPN to the internet it would be nice to be able to configure AllowedIPs as a global set of ips for all peers via env var or per client in the web interface.

Thanks!

**Comment by DerDanilo** [comment]
Also missing this feature. It's a must have. I patched it into PiVPN and now this awesome simple GUI moved away from PiVPN.
It should also be possible to update existing client profiles with this in case IPs have changed.

Thanks!

**Comment by WeeJeWel** [comment]
If you patched it, create a PR! :D

**Comment by DerDanilo** [comment]
As written in the PR, I never touched java code. Hope that this is correct.

Are client profiles also updated on variable changes? If not it should please be implemented.

**Comment by WeeJeWel** [comment]
Merged
