### ISSUE TITLE
Anyway to Disable network charts/graph in UI ?

### ISSUE THREAD

**Issue by benisai** [WeeJeWel/wg-easy#195]
I want to disable the newly added network bandwidth charts / graph. 
The UI is very slow with 10 clients running, I suspect it's the graph. How can this be disabled? My VPS is pretty powerful, 3vcpu and 3.5gb ram, and the UI is just slow/terrible to use.

**Comment by ApexioDaCoder** [comment]
The ui is client rendered, so how powerful the vps is does not matter.

**Comment by benisai** [comment]
> The ui is client rendered, so how powerful the vps is does not matter.

It's slow on both my note 10+ and surface pro 4. Both devices have enough power to render it. The UI is just slow with those charts, can't explain why, I'm no expert.

**Comment by benisai** [comment]
I'd like to disable them anyhow, they don't really help much.

**Comment by ApexioDaCoder** [comment]
Just clone the repo and remove this div: https://github.com/WeeJeWel/wg-easy/blob/bbd19b7a6f390d95d80aab75271a24b92f6c591e/src/www/index.html#L75

**Comment by ApexioDaCoder** [comment]
And the div right bellow: https://github.com/WeeJeWel/wg-easy/blob/bbd19b7a6f390d95d80aab75271a24b92f6c591e/src/www/index.html#L79
