### ISSUE TITLE
It's not compatible with Nftables

### ISSUE THREAD

**Issue by q2dg** [WeeJeWel/wg-easy#2]
I've seen it uses Iptables instead...

**Comment by WeeJeWel** [comment]
Sorry, but what is the issue exactly?

**Comment by q2dg** [comment]
Well, nftables is replacing Iptables in major distributions (Ubuntu, Fedora, Arch, etc)

**Comment by WeeJeWel** [comment]
So? Doesn't it work for you or...?

**Comment by q2dg** [comment]
Well, it works if I install "iptables" package, which isn't currently installed by default

**Comment by WeeJeWel** [comment]
I don't understand. iptables is installed _inside_ the container. Why do you need to install it on your host?

**Comment by q2dg** [comment]
Ah, ok. I though "wg-easy" could be installed in the main host system too. Sorry for my ununderstanding of the tool and for the inconvenience. Feel free to close this issue-
