### ISSUE TITLE
a bug similar to #139

### ISSUE THREAD

**Issue by idnewnil** [WeeJeWel/wg-easy#200]
https://github.com/WeeJeWel/wg-easy/blob/bbd19b7a6f390d95d80aab75271a24b92f6c591e/src/www/js/api.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L9

/api => ./api

**Comment by WeeJeWel** [comment]
Fixed
