### ISSUE TITLE
dns not working

### ISSUE THREAD

**Issue by smilence86** [WeeJeWel/wg-easy#203]
Hello,

Thanks for your project, Let's start wireguard easy and quickly.

But I found only ip:port works, domain not working, this is my startup script:

```
docker run -d \
 --name=wireguard \
 -e WG_HOST=vpn.example.com \
 -e PASSWORD=myPwd \
 -e WG_DEFAULT_DNS=10.13.1.8 \
 -v /home/www/wireguard/wg-easy:/etc/wireguard \
 -p 51820:51820/udp \
 -p 51821:51821/tcp \
 --cap-add=NET_ADMIN \
 --cap-add=SYS_MODULE \
 --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
 --sysctl="net.ipv4.ip_forward=1" \
 --restart unless-stopped \
 weejewel/wg-easy
```

10.13.1.8 is a dns server in lan network,  And there is a web service that is 10.13.1.9:80, It's been serve by nginx, such as "web.example.com", When vpn connected in other net, I can visit web service only "ip:port", but not domain.

I want to visit web service use domain "https://web.example.com" instead of ip:port.

Is there something wrong or missing? How can I debug it, Thanks.

**Comment by Teraskull** [comment]
Because domain is managed by the reverse proxy, dns has nothing to do with ports.

**Comment by smilence86** [comment]
> Because domain is managed by the reverse proxy, dns has nothing to do with ports.

Thanks for you reply.

Yes I have used reverse proxy with nginx, In lan network domain works well, But in other network which vpn connected, I can't use domain to visit my web site.

**Comment by smilence86** [comment]
I resolved it, The reason is my phone chrome has been setted private dns query, So the dns in lan will not work, I switch it to "Automatic", All services works perfect.

Thanks.

**Comment by quyleanh** [comment]
@smilence86 are you using Adguard Home/Pihole server as DNS server?

I selfhost Aguard Home for my network with docker, but I still cannot manage to setup `wg-easy` to use this Adguard Home as DNS server. Do you know how to config?

**Comment by smilence86** [comment]
@quyleanh Yes, I'm using Adguard Home, It's deployed in openwrt.

If your adh's ip is 192.168.2.10, you just need set parameter "WG_DEFAULT_DNS" with same ip.

**Comment by quyleanh** [comment]
@smilence86 thanks
I tried but there is resolve error. DNS server does not work.

You can see my internet device here:
```
1: lo    inet 127.0.0.1/8 scope host lo\       valid_lft forever preferred_lft forever
2: eth0    inet 192.168.0.123/24 brd 192.168.0.255 scope global eth0\       valid_lft forever preferred_lft forever
4: br-33a01c9e0c73    inet 172.21.0.1/16 brd 172.21.255.255 scope global br-33a01c9e0c73\       valid_lft forever preferred_lft forever
5: docker0    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0\       valid_lft forever preferred_lft forever
43: br-55dd916d7635    inet 172.26.0.1/16 brd 172.26.255.255 scope global br-55dd916d7635\       valid_lft forever preferred_lft forever
```

My Raspberry is on `192.168.0.123` address and handle all DNS request.
Adguard Home is docker on Raspberry with `172.21.0.1` network address.

I enter both `192.168.0.123` and `172.21.0.1` but it does not work.

**Comment by ngophuong** [comment]
> Thank you for your suggestion. I did some research and found the solution. These two docker need to connect each other. So we have to define the network for `wg-easy`.
> 
> Since I use docker version, I add the following config to `docker-compose.yml` file of `wg-easy`
> 
> ```yaml
> networks:
>   default:
>     external:
>       name: adguard-home_default
> ```
> 
> Hope someone found helpful.

thank you, could you help share in the end, how to set the DNS server follow your AdGuard home IP dynamic? Since every time you restart the  Raspberry the docker will generate a new ip address for your AdGuard home right ?

**Comment by quyleanh** [comment]
@ngophuong I don't remember how I fix it. But you can try to config as the following UFW rule.
```
[11] 53                         ALLOW IN    172.16.0.0/12
[12] 53                         ALLOW IN    10.0.0.0/8
[13] 53                         ALLOW IN    192.168.0.0/16
```

**Comment by ngophuong** [comment]
@quyleanh  thank you for quick update 👍 
For me, i made it by:
1. Assign static ip for pihole container
2. putting two container (pihole +wg-easy) in the same network
3. Assign WG_DEFAULT_DNS to pihole container ip

**Comment by quyleanh** [comment]
@ngophuong so does it work for you? What is your problem?

**Comment by quyleanh** [comment]
@ngophuong could you please tell me how did you config your docker-compose file for getting static ip? I've just reinstall Adguard Home and couldn't manage to config.

Thank you.

**Comment by ngophuong** [comment]
@quyleanh  for me, i assign the static IP to the WG as below
`
version: "3.8"
services:
  wg-easy:
    environment:
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=xxx

      # Optional:
      - PASSWORD=homewg
      # - WG_PORT=51820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=172.21.0.5
      #- WG_ALLOWED_IPS=192.168.1.0/24
      
    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - .:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

networks:
  default:
    external:
      name: web
      

`

**Comment by quyleanh** [comment]
@ngophuong what is about your pihole docker-compose file? Could you please post it here?

**Comment by ngophuong** [comment]
here is my config for pihole, assign the Ip address directly to Pihole @quyleanh 

`
restart: unless-stopped
    networks:
      web:
        ipv4_address: 172.21.0.5

networks:
  web:
    external: true
`
