### ISSUE TITLE
[Feature Request] Unable to set Wg<> Device

### ISSUE THREAD

**Issue by ryand11** [WeeJeWel/wg-easy#208]
Not Sure if this is possible, but worth the ask:

Running two instances on the same server, however unable to set the network device automatically. Ideally, one container would run on wg0 and other on wg1 etc. Not sure if this is possible to pass in as an env variable.

**Comment by WeeJeWel** [comment]
You'd need to replace all `wg0` occurrences with something defined in `config.js`.

If you want this, feel free to branch.
