### ISSUE TITLE
ssh impossible from connected client

### ISSUE THREAD

**Issue by mightysashiman** [WeeJeWel/wg-easy#217]
For some unknown reason, I cannot ssh into my box which runs wg-easy stack from any of the peers which successfully connect to the wireguard server. With 10.8.0.1 being the wireguard server IP, ssh -v pi@10.8.0.1 gives :
```
debug1: Connecting to 10.8.0.1 [10.8.0.1] port 22.
debug1: connect to address 10.8.0.1 port 22: Connection refused
ssh: connect to host 10.8.0.1 port 22: Connection refused
```

did not have any such issue running wireguard through pivpn previously.

Thanks in advance for the help !

**Comment by WeeJeWel** [comment]
You're trying to SSH into the Docker container, which doesn't run a SSH server.

Try SSH'ing into `172.17.0.1` when connected to WireGuard.

**Comment by david-plugge** [comment]
While this works, i would rather like using the actual ip address of the machine. Any idea how to achieve that? Or would it just be a bad workaround?
