### ISSUE TITLE
not able to add to wg0.conf

### ISSUE THREAD

**Issue by docfactory37** [WeeJeWel/wg-easy#219]
im trying to add DNS and other config items to wg0.conf, i can add the entries but when i restart the container it resets the file.

can can i make the change persistent?

i have it linked to a persistent volume on the host

**Comment by Joeyprc1** [comment]
I would also like to make persistent changes to the wg0.conf file. Trying to add allowed ips to the server conf.

**Comment by eandersons** [comment]
Environment variables can be used to achieve the mentioned (see the section ["Options](/WeeJeWel/wg-easy#options) in [`README.md`](/WeeJeWel/wg-easy/blob/master/README.md)):

- `WG_DEFAULT_DNS` to specify custom DNS servers;
- `WG_ALLOWED_IPS` to specify allowed IP addresses.

**Comment by MasterSmurf** [comment]
> 

This is working, but only for the clients.

Is it possible to edit 'allowed IPs' for peers as well?

**Comment by Joeyprc1** [comment]
If it helps at all I applied the rules as mentioned in the read me. It does not affect the server conf file but it does work for the dns(at least it sets the client dns settings correctly). I’m trying to set up allowed ips for a specific client to allow communication across the vpn clients. I adjusted the server conf file and it worked briefly before the setting were reset.

**Comment by kennethklee** [comment]
from the looks of it, may prove difficult to preserve conf on the server.

perhaps break this into multiple issues?

looks like two:

* setting to change a peer into an egress gateway with allowed ips?
* `wg_dns` env config?

**Comment by WeeJeWel** [comment]
This is not possible. Please create an issue for each setting you'd like to modify.
