### ISSUE TITLE
support https

### ISSUE THREAD

**Issue by ragnarok22** [WeeJeWel/wg-easy#22]
This wg-easy actually don't support https request. Any chance to add into the roadmap? btw: great job! Simple and nice!

**Comment by WeeJeWel** [comment]
Nope. Please add nginx or so in front of it.

**Comment by WeeJeWel** [comment]
And thanks :)

**Comment by Fastidious** [comment]
> Nope. Please add nginx or so in front of it.

The ability to bind wg-easy to localhost only would make your recommendation cleaner. All it takes is a variable (with a `0.0.0.0` default value) and changing two files.

**Comment by WeeJeWel** [comment]
Why? It's inside the container so it doesn't matter.

**Comment by Murzik2142** [comment]
Access to the container implies access through the Internet and assume that the password will be transmitted in open form.
Especially if deployed on VPS/VDS
