### ISSUE TITLE
Feature request: Display totol bytes received and sent

### ISSUE THREAD

**Issue by shizunge** [WeeJeWel/wg-easy#221]
Wireguard natively display the total bytes received and sent.
Could you please add it to the UI in addition to (or replacing) the receiving/transmitting rate.

wg-easy is not a good tool for monitoring the network traffic (and it is not designed to be such a tool), so I think total byte over a period seems more useful than the rate.

**Comment by Albuca** [comment]
If you hover your mouse over the current upload/download rate, it will give you the total for the session.

Should just be a matter of changing the HTML on the page to display the values without having to hover the mouse -- which would be my preference tbh

**Comment by shizunge** [comment]
Thanks. Good to know.
Unfortunately, there is no mouse on a cellphone, when I viewed the page on mobile.
