### ISSUE TITLE
Invalid tunnel name

### ISSUE THREAD

**Issue by turicas** [WeeJeWel/wg-easy#226]
I've created a client named "Turicas - Notebook", downloaded the `.conf` and got a message from WireGuard client that the client name is invalid (like [this report](https://www.reddit.com/r/WireGuard/comments/i74nv5/unable_to_import_tunnel_invalid_name/)). I just renamed the file to "turicas_notebook.conf" and it worked.
I suggest "slugifying" the client name before creating the .conf file.
A simple code to solve this would be something like:

```javascript
let clientName = "Turicas - Notebook";
let fixedClientName = clientName.toLowerCase().replace(/[^A-Za-z0-9]/g, '_').replace(/_+/, '_')
```

**Comment by WeeJeWel** [comment]
Is this still an issue? See https://github.com/WeeJeWel/wg-easy/blob/master/src/lib/Server.js#L102
