### ISSUE TITLE
Unable to import tunnel: cannot parse endpoint ".../24:52820" in Peer's Endpoint: Forbidden characters

### ISSUE THREAD

**Issue by turicas** [WeeJeWel/wg-easy#227]
I have the following problem when importing a `.conf` or scanning a QRcode created using wg-easy:

![wireguard-error](https://user-images.githubusercontent.com/186126/159099998-bbd86e70-bc60-47de-ab32-a235036e9394.jpeg)

I edited the `.conf` file, removed the "/24" from the `Endpoint` line and it worked.

EDIT: it was my fault, I added the "/24" in `WG_HOST` when running the container. Is it possible to change the code just to check if `WG_HOST` is in the correct format (an IP address)?

**Comment by harshraj21** [comment]
> > I guess you are using ipv6, simply cover your ipv6 address with square brackets and that should fix the issue. eg: if your ipv6 address is -> 1dd0:09d6:7bba:5be2:bf10:7fb6:32e6:1dfa then you should mention in the config as -> [1dd0:09d6:7bba:5be2:bf10:7fb6:32e6:1dfa].
> > Simply that should fix the issue.
> 
> But I'm not using IPv6 - you can see it's an IPv4 on the screenshot.

no need to mention subnet in the ipv4. simply remove the subnet. and it should work.

**Comment by turicas** [comment]
> no need to mention subnet in the ip. simply remove the subnet. and it should work. ie: change -> X:X:X:X/24 to X:X:X:X

@harshraj21, I edited the description with: "EDIT: it was my fault, I added the "/24" in WG_HOST when running the container. Is it possible to change the code just to check if WG_HOST is in the correct format (an IP address)?"

**Comment by harshraj21** [comment]
> > no need to mention subnet in the ip. simply remove the subnet. and it should work. ie: change -> X:X:X:X/24 to X:X:X:X
> 
> @harshraj21, I edited the description with: "EDIT: it was my fault, I added the "/24" in WG_HOST when running the container. Is it possible to change the code just to check if WG_HOST is in the correct format (an IP address)?"

yes you can make use of regex to check for errors in the ip.
