### ISSUE TITLE
Feature request: Usage statistics

### ISSUE THREAD

**Issue by stalinReturn** [WeeJeWel/wg-easy#239]
It would be nice if traffic statistics for each user were stored in a database. And conventionally there would be a separate tab on the website to view full information with graphs. This would be useful for those who rent servers with limited traffic. At the moment, when the server is rebooted, the information is reset to zero.

**Comment by WeeJeWel** [comment]
Sure, go ahead and make a PR!

**Comment by stalinReturn** [comment]
I'm not quite sure what that answer was about?

**Comment by sorcer1122** [comment]
> I'm not quite sure what that answer was about?

Basically, @WeeJeWel offered you to do it yourself. PR is a contribution you can do, and, if it is good enough, it will be merged with the rest of wg-easy. I also need this feature but not very capable of handling PRs.
