### ISSUE TITLE
iptables always configures 51820, regardless of WG_PORT 

### ISSUE THREAD

**Issue by zilexa** [WeeJeWel/wg-easy#24]
WG_PORT value is not used when the container starts and configures IPTABLES

My compose: 

```
##____________________ WG-easy [Management/VPN]
  VPN-wg-easy:
    container_name: VPN-wg-easy
    image: weejewel/wg-easy
    restart: always
    networks: 
      - management
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      WG_HOST: $DOMAIN
      PASSWORD: $PW_EXT
      WG_PORT: 51822
      WG_DEFAULT_ADDRESS: 10.6.0.x
      WG_DEFAULT_DNS: 192.168.88.2 #this is the LAN IP of localhost, dns goes via AdGuardHome/Unbound (both in docker)
    volumes:
      - $DOCKERDIR/VPN-wg-easy:/etc/wireguard
    ports:
      - 51822:51822/udp
      - 5100:51821/tcp
    restart: unless-stopped
```

Regardless of the WG_PORT value, the log shows:
```
2021-06-01T11:40:23.965Z Server Listening on http://0.0.0.0:51821,
2021-06-01T11:40:23.965Z WireGuard Loading configuration...,
2021-06-01T11:40:23.967Z WireGuard Configuration loaded.,
2021-06-01T11:40:23.967Z WireGuard Saving config...,
2021-06-01T11:40:23.967Z WireGuard Config saved.,
$ wg-quick up wg0,
$ iptables -t nat -A POSTROUTING -s 10.6.0.0/24 -o eth0 -j MASQUERADE,
$ iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT,
$ iptables -A FORWARD -i wg0 -j ACCEPT,
$ iptables -A FORWARD -o wg0 -j ACCEPT,
2021-06-01T11:40:24.033Z WireGuard Syncing config...,
$ wg syncconf wg0 <(wg-quick strip wg0),
2021-06-01T11:40:24.048Z WireGuard Config synced.,
```

And no client can access the server, because in my case port 51820/udp is not open. 

As a workaround, to deviate from the default 51820/udp, I had to remove the WG_PORT env variable and changed my ports section: 

```
    ports:
      - 51822:51820/udp
```

**Comment by WeeJeWel** [comment]
Port 51820 is hardcoded. Simply map 51820 to 51822 using docker-compose and you're done.

**Comment by zilexa** [comment]
But huh, what is the purpose then of WG_PORT?

Note my last line: I really do not mind mapping using docker-compose, but the README clearly states you can use WG_PORT and I did that properly.. this way, I looked in other directions for the culprit.

**Comment by WeeJeWel** [comment]
WG_PORT will be put in the client's .conf file, e.g. vpn.myhost.com:51822.

**Comment by zilexa** [comment]
OMG  sorry I should have realized that, makes total sense! Thanks for pointing it out. 
Indeed, the client config now has 51822, I don't have to modify that manually anymore :+1:

**Comment by WeeJeWel** [comment]
No prob, have fun!
