### ISSUE TITLE
Cannot find device "wg0"

### ISSUE THREAD

**Issue by Ctaeth** [WeeJeWel/wg-easy#245]
Hello.

Recently did a few updates, one of which was kernel update. Since then I've been getting the following:
```
Error: WireGuard exited with the error: Cannot find device "wg0"
This usually means that your host's kernel does not support WireGuard!
    at /app/lib/WireGuard.js:63:19
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /app/lib/WireGuard.js:61:9
```
Any suggestions on how to get it up and running again?

**Comment by JesusRo** [comment]
Hi @Ctaeth,

The exactly same happened to me today, after a reboot where the kernel was upgraded of the host (I have wg-easy running on k3s)

Solution for me was to install `wireguard-tools` on the underlaying host debian which also installed the dkms module.
Give it a try

**Comment by Ctaeth** [comment]
@JesusRo thanks for the reply buddy!

So i've installed wireguard-tools (and dkms) on the host debian. I assume you mean NOT in the container, but on the actual host right? I'm still very newbie to selfhosting.

I'm still getting the same issue and the logs still show exactly the same thing.

**Comment by yllekz** [comment]
On my Linux server I had to run ``sudo apt install wireguard wireguard-tools resolvconf`` and reboot. wg-easy provides the front-end but you need to sideload in some of the actual WireGuard components for it to function properly.

**Comment by fut33v** [comment]
same issue on Ubuntu 20.04 
with kernel 5.4.0 
all of the steps with install wireguard tools and resolvconf didn't help

**Comment by Ctaeth** [comment]
> On my Linux server I had to run `sudo apt install wireguard wireguard-tools resolvconf` and reboot. wg-easy provides the front-end but you need to sideload in some of the actual WireGuard components for it to function properly.

Apologies for the delay in replying (I'm blaming sickness on that). Tried those steps and still getting the same issue. Do you do anything else other than installing those 3 things and rebooting?

**Comment by fut33v** [comment]
Ok this was the issue with no kernel module wireguard on VPS machine, as a result I changed my VPS provider to better one=)

**Comment by Ctaeth** [comment]
Not sure if this will help in cases such as @fut33v but I have managed to fix it now.

[this answer](https://askubuntu.com/a/1195346) gave me the solution:
`sudo modprobe wireguard` was giving me an error; if it doesnt, i guess it means its already installed and you dont have the same issue as me.
`sudo apt-get install linux-headers-$(uname -r)` to install the headers needed
`sudo apt-get remove wireguard` followed by `apt-get install wireguard`
Didnt have to reboot the server nor docker for it to get fixed.

**Comment by m0x61h0x64i** [comment]
> `sudo apt-get install linux-headers-$(uname -r)` to install the headers needed

root@Blaan:~#  sudo apt-get install linux-headers-$(uname -r)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package linux-headers-5.2.0
E: Couldn't find any package by glob 'linux-headers-5.2.0'
E: Couldn't find any package by regex 'linux-headers-5.2.0'
