### ISSUE TITLE
Can't ping lans address 

### ISSUE THREAD

**Issue by Ganzhans** [WeeJeWel/wg-easy#246]
in an other issue I begun about WG-easy  and Pi-hole ...... but ik won't work anymore

container is up and running
web site also running and can add users
QR code shows up and create a client entry
make the connection ok, but can't ping to lan addresses and surf on internet
is see my DNS on the wg client is 1.1.1.1 but when I use the -e WG_DEFAULT_DNS and put a address no effect on the client.

what's going wrong ?

ps the normal WG docker (without guil works ) 

regards Hans

**Comment by Ganzhans** [comment]
removed and recreated the mapped /etc/wireguard folder ......
the vpn is woking included browsing on internet, but not  via Pi-hole, the DNS Server in the client is 1.1.1.1
ip range for clients 10.8.0.x  

so how to configure to work with the pi-hole DNS

**Comment by Koomongous** [comment]
Change the environment 'WG_DEFAULT_DNS' to the IP of the device Pi-Hole is on. You can also change it manually on the client.

**Comment by ShlomiD83** [comment]
Your Pi Hole is on a separate macvlan?
