### ISSUE TITLE
Docker logs filled with "wg show wg0 dump" every second

### ISSUE THREAD

**Issue by justifiably** [WeeJeWel/wg-easy#25]
See docker-compose logs, can we disable this?  Thanks for wg-easy!

today at 17:23:45 $ wg show wg0 dump
today at 17:23:46 $ wg show wg0 dump
today at 17:23:47 $ wg show wg0 dump
today at 17:23:48 $ wg show wg0 dump
today at 17:23:49 $ wg show wg0 dump
today at 17:23:50 $ wg show wg0 dump
today at 17:23:51 $ wg show wg0 dump
today at 17:23:52 $ wg show wg0 dump
today at 17:23:53 $ wg show wg0 dump
today at 17:23:54 $ wg show wg0 dump
today at 17:23:55 $ wg show wg0 dump
today at 17:23:56 $ wg show wg0 dump
today at 17:23:57 $ wg show wg0 dump
today at 17:23:58 $ wg show wg0 dump
today at 17:23:59 $ wg show wg0 dump
today at 17:24:00 $ wg show wg0 dump
today at 17:24:01 $ wg show wg0 dump
today at 17:24:02 $ wg show wg0 dump
today at 17:24:03 $ wg show wg0 dump
today at 17:24:04 $ wg show wg0 dump
today at 17:24:05 $ wg show wg0 dump
today at 17:24:06 $ wg show wg0 dump
today at 17:24:07 $ wg show wg0 dump
today at 17:24:08 $ wg show wg0 dump
today at 17:24:09 $ wg show wg0 dump
today at 17:24:10 $ wg show wg0 dump
today at 17:24:11 $ wg show wg0 dump
today at 17:24:12 $ wg show wg0 dump
today at 17:24:13 $ wg show wg0 dump
today at 17:24:14 $ wg show wg0 dump
today at 17:24:15 $ wg show wg0 dump
today at 17:24:16 $ wg show wg0 dump
today at 17:24:17 $ wg show wg0 dump
today at 17:24:18 $ wg show wg0 dump
today at 17:24:19 $ wg show wg0 dump
today at 17:24:20 $ wg show wg0 dump
today at 17:24:21 $ wg show wg0 dump
today at 17:24:22 $ wg show wg0 dump
today at 17:24:23 $ wg show wg0 dump
today at 17:24:24 $ wg show wg0 dump
today at 17:24:25 $ wg show wg0 dump
today at 17:24:26 $ wg show wg0 dump
today at 17:24:27 $ wg show wg0 dump
today at 17:24:28 $ wg show wg0 dump

**Comment by WeeJeWel** [comment]
Yeah, close the Web UI ;)
