### ISSUE TITLE
Splash screen before Web UI logon prompt

### ISSUE THREAD

**Issue by iAmSaugata** [WeeJeWel/wg-easy#251]
Every time I opened the Web UI, it is showing me this initially for just a few milliseconds and then prompting to the logon screen, is this normal?
![image](https://user-images.githubusercontent.com/26755120/165450682-2aee2657-9e7a-4896-9207-b49d0c41cf61.png)

**Comment by Teraskull** [comment]
This UI bug is fixed in my pull request #178.

Unfortunately, the dev does not want to merge it because of "bland color style", so you have to manually copy the edited file contents into the container, or rebuild the docker image from my fork.

**Comment by ZyanKLee** [comment]
> This UI bug is fixed in my pull request #178.
> 
> Unfortunately, the dev does not want to merge it because of "bland color style", so you have to manually copy the edited file contents into the container, or rebuild the docker image from my fork.

Could you perhaps be persuaded into creating a PR just for the fix of this bug?

**Comment by Teraskull** [comment]
@ZyanKLee Sure, that makes sense. I'll get around it as soon as possible.
