### ISSUE TITLE
Feature request: Update client configs when updating WG_HOST

### ISSUE THREAD

**Issue by a-waider** [WeeJeWel/wg-easy#253]
Hey, it would be nice to sync the WG_HOST environment variable with the host inside the config files of all clients. 

Current behaviour:
Currently the config file remains with the WG_HOST which was at the time of creating the client. If you then change the WG_HOST to another host and try to reconnect a client with the same config in the web UI then it won't work because the endopoint still points to the old WG_HOST.

New behaviour:
Once you change the WG_HOST environment variable the program will update the endpoint in all clients configuration. 
The same behaviour would be nice for all other wireguard specific configuration options.

**Comment by WeeJeWel** [comment]
Um, how would you change this configuration on a client’s machine automatically?

**Comment by a-waider** [comment]
I don't want to change the configuration on the client's machine. My intention was to change the client configuration on the wireguard server.

Here is an example workflow:
1. set WG_HOST to foo
2. Add client configuration
3. Add phone e.g. by qr code
4. change WG_HOST in docker run command to bar
    -> This should change the client configurations on the wireguard maschine
6. Update phone by rescanning the qr code (with updated WG_HOST)

**Comment by WeeJeWel** [comment]
That’s not how it works. The client configuration is generated on the fly when it’s being downloaded/scanned.
