### ISSUE TITLE
Triggering Google Phishing

### ISSUE THREAD

**Issue by TolleyLikesRice** [WeeJeWel/wg-easy#256]
Hi, I have installed wg-easy, and put it on a subdomain. Now my whole domain has been flagged for phising, displaying warning pages to users. No idea why this has been triggered by this app.

**Comment by TolleyLikesRice** [comment]
![image](https://user-images.githubusercontent.com/39429061/167270900-3b869f63-44f6-4a42-9b2b-fb865f989773.png)

**Comment by WeeJeWel** [comment]
¯\_(ツ)_/¯
