### ISSUE TITLE
Dockerfile should expose port 51821, not port 80?

### ISSUE THREAD

**Issue by justifiably** [WeeJeWel/wg-easy#26]
I think web UI is on 51821, nothing is on port 80?  Thanks for wg-easy!

**Comment by WeeJeWel** [comment]
Inside the container it's on port 80.

**Comment by justifiably** [comment]
Hmm, not according to your docker-compose file and the current image on Docker hub I tried, but never mind.

```
docker run -e WG_HOST=localhost weejewel/wg-easy
2021-06-02T10:19:34.977Z Server Listening on http://0.0.0.0:51821
2021-06-02T10:19:34.978Z WireGuard Loading configuration...
```

**Comment by WeeJeWel** [comment]
Oh sorry you're right. Where did you read port 80 was used though?

**Comment by justifiably** [comment]
Dockerfile exposes port 80, plus you can see it from `docker-compose ps`.   No biggie but it confused the auto reverse proxy I use (<https://github.com/nginx-proxy/nginx-proxy>)

**Comment by WeeJeWel** [comment]
Ooops, fixed!

**Comment by justifiably** [comment]
Ta!
