### ISSUE TITLE
UI is VERY laggy/slow with multiple users. 

### ISSUE THREAD

**Issue by benisai** [WeeJeWel/wg-easy#261]
Hello, I have 13 users configured on my WG. My VPS is pretty powerful, 3 vcpu with 3.5GB ram. Still, the webpage is very laggy when adding a new user. My phone is a Note 10+ with 12gb ram and 8 cores, so it's not my device (I can load heavier pages just fine). 
This is a bug, can you please look / update the app.

**Comment by benisai** [comment]
Same issue on my surface pro 4. 

This has to be a code issue on the WG itself.

**Comment by a-stankevich** [comment]
I notice this as well, the UI becomes laggy for me after 6-8 users. 
CPU becomes loaded with multiple apexcharts updating at the same time
![image](https://user-images.githubusercontent.com/6768522/172687995-0b269c69-41af-40ce-98c8-ef1f99a98f2b.png)

**Comment by benisai** [comment]
@WeeJeWel -- we need to remove these charts or have a way to hide them via environment variables.

**Comment by WeeJeWel** [comment]
Fixed in a72029d7e5dd0e7ac26acdd93e6aee939c6b8a52

**Comment by benisai** [comment]
Thanks @WeeJeWel
