### ISSUE TITLE
docker-compose: vpn doesn't work in bridge network mode

### ISSUE THREAD

**Issue by x1unix** [WeeJeWel/wg-easy#262]
Hi. I used an example from `docker-compose.yml` file and created a container.

I was able to connect to the server and I saw incoming packets on web UI stats page but was unable to ping anything (even server itself).

Looks like the problem that wireguard in container received RX packets but was unable to send TX packets.

I found a temporary workaround: use host network: `network_mode: host`.

Can you please suggest a better solution please?

**Comment by mkono87** [comment]
I for some reason cant even change the network from bridge to host. I can remove it from bridge but not add to host.

**Comment by WeeJeWel** [comment]
No idea, probably some misconfiguration on your host.
