### ISSUE TITLE
[Question] Change web UI port 51821

### ISSUE THREAD

**Issue by amalcev** [WeeJeWel/wg-easy#268]
Hi,
Is there a way to change web UI port 51821 either during installation or after?
Thanks

**Comment by eandersons** [comment]
First of all, your question belongs to [discussions](/WeeJeWel/wg-easy/discussions).

Secondly, too less information is provided in your question.
What exactly is your desired outcome? What have you already tried? How did you launch WireGuard Easy container (with `docker run` or `docker-compose`)?

Nevertheless, most probably your question could be resolved with port mapping - change the value before `:` to your desired value: relevant part in `docker run` command is `-p 51821:51821/tcp` and `- "51821:51821/tcp"` in [`docker-compose.yml`](/WeeJeWel/wg-easy/blob/master/docker-compose.yml).

**Comment by amalcev** [comment]
Thank you! My issue is solved now.
