### ISSUE TITLE
Do not hardcode eth0 in src/config.js

### ISSUE THREAD

**Issue by gi-yt** [WeeJeWel/wg-easy#270]
src/config.js:iptables -t nat -A POSTROUTING -s ${module.exports.WG_DEFAULT_ADDRESS.replace('x', '0')}/24 -o eth0 -j MASQUERADE;
in this line in src/config.js, wireguard is hardcoded which makes it break on computers that use a different interface for ethernet.
I am not  sure how to fix  this since i know practically 0  javascript.
Workaround for now is to just change eth0 to my ethernet port (ens3) but a more long term plan would be appreciated

Regards,
Arya

**Comment by WeeJeWel** [comment]
You can set `WG_POST_UP` environment variable.
