### ISSUE TITLE
The downloaded config does not work on MacOS

### ISSUE THREAD

**Issue by ErikThiart** [WeeJeWel/wg-easy#277]
Mac seems to want a .zip file and not a .cfg file

**Comment by Genesis-Fire** [comment]
My Mac doesn't have this issue.

**Comment by WeeJeWel** [comment]
Cannot reproduce.

**Comment by regs79** [comment]
I had the same issue, Wireguard on macOS wouldn't import a .cfg file. If I you change the extension to .conf it should import fine.

Just wanted to leave a comment in case anyone else has this issue.
