### ISSUE TITLE
How can I change the DNS server after wiregaurd got installed?

### ISSUE THREAD

**Issue by ErikThiart** [WeeJeWel/wg-easy#279]
I have it running in docker without issue.

I then installed Pi Hole

I now want to force all the WireGaurd traffic to use Pi Hole

I have no idea how to do it, it would be nice to have that functionality in the GUI to change DNS servers and stuff.

**Comment by eandersons** [comment]
Your chances to achieve what you are aiming for could be greatly improved if you read the documentation.

Most probably the environment variable `WG_DEFAULT_DNS` (from the section [Options](https://github.com/WeeJeWel/wg-easy#options)) is what you are looking for.

**Comment by ErikThiart** [comment]
I read that, the thing is, I am so new to docker, my understanding is I had to do that during the creation phase, but I already created this container.

So how do I update WG_DEFAULT_DNS after the fact?

does that make sense?

**Comment by eandersons** [comment]
> So how do I update WG_DEFAULT_DNS after the fact?

It depends on the way you created the WireGuard container.
In general you should recreate the container with the desired environment variable values.

**Comment by ErikThiart** [comment]
Won't I then lose all the clients I created via the GUI?

**Comment by WeeJeWel** [comment]
No, these are stored in your 'volume'.

**Comment by ErikThiart** [comment]
Don't think I created a volume?

I used these steps from your documentation;

$ docker run -d \
  --name=wg-easy \
  -e WG_HOST=🚨YOUR_SERVER_IP \
  -e PASSWORD=🚨YOUR_ADMIN_PASSWORD \
  -v ~/.wg-easy:/etc/wireguard \
  -p 51820:51820/udp \
  -p 51821:51821/tcp \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --restart unless-stopped \
  weejewel/wg-easy

**Comment by WeeJeWel** [comment]
It's in `~/.wg-easy`.

**Comment by ErikThiart** [comment]
Thank you 

( still new to docker )
