### ISSUE TITLE
Traffic statistics needed in the UI

### ISSUE THREAD

**Issue by Genesis-Fire** [WeeJeWel/wg-easy#280]
Hi, is it possible to add “traffic statistics" in current WG UI? So we can know how much traffic is used for each peer. Thanks

**Comment by WeeJeWel** [comment]
Hover over the download/upload speed for totals.

**Comment by Genesis-Fire** [comment]
> Hover over the download/upload speed for totals.

But when I hover over the download/upload speed, nothing show up.
