### ISSUE TITLE
Stuck and slowed down the page after creating and connecting 20 users to the server

### ISSUE THREAD

**Issue by geekfig** [WeeJeWel/wg-easy#287]
After running the software with docker -compose version 2.6.0 and docker version 20, the software comes up well and up to 20 users that are created in the web user interface, the web user interface page strongly engages the system resources about 2 GB RAM and CPU are just as big and the screen is very slow and locks and hangs and nothing can be done anymore.

**Comment by avgordeev** [comment]
I also have problems with resource usage. Web UI uses about 25% of the processor and 1 GB of memory

**Comment by WeeJeWel** [comment]
This is now fixed in v7.
