### ISSUE TITLE
Problem with the update

### ISSUE THREAD

**Issue by fcaolpa** [WeeJeWel/wg-easy#288]
Hello mate, today I got the red message indicating that an update is available.
I proceeded to click on the update icon and when I saw the update procedure I couldn't get it to work and the container got corrupted. Luckily I always make a backup and I was able to restore it.
Is there something I'm missing?

Thank you very much.

Updating

To update to the latest version, simply run:

docker stop wg-easy
docker rm wg-easy
docker pull weejewel/wg-easy

docker run -d \

**Comment by geekfig** [comment]
hellow dude

you can use this handy tool to update the container to latest version of github

link of how to use it:

https://www.the-digital-life.com/watchtower/

**Comment by fcaolpa** [comment]
Thanks, I'll take a look at it and test what you tell me.

**Comment by geekfig** [comment]
i personly use it on this same wg-easy container and update it without any dataloss 
the youtube video of the using process: 

https://youtu.be/5lP_pdjcVMo

**Comment by geekfig** [comment]
your welcome
