### ISSUE TITLE
Problem update

### ISSUE THREAD

**Issue by DenisG1302** [WeeJeWel/wg-easy#289]
When updating according to the instructions, when entering the command 
`docker pull weejewel/wg-easy`
writes `Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 127.0.0.1:53: server misbehaving`
How to fix it?

**Comment by geekfig** [comment]
heloww 

use this methode to update the container without dataloss

the youtube video of the using process:

https://youtu.be/5lP_pdjcVMo

**Comment by DenisG1302** [comment]
When entering commands from the link, it gives the same error

**Comment by geekfig** [comment]
it seems the docker engine has a error 
restart docker service or re install it
