### ISSUE TITLE
Container fails to start after a system reboot

### ISSUE THREAD

**Issue by oaltakrouri** [WeeJeWel/wg-easy#295]
I noticed that whenever I reboot my machine, the container can not restart itself until I use 

` sudo fuser -k 51820/udp`
 
 to kill and free up port 51820.

Error shown below:

```
docker start wg-easy
Error response from daemon: driver failed programming external connectivity on endpoint wg-easy (39e91277fd349b0034a22ea158d5ce6e6c96e5b86c999eb191be81e48e354f06): Error starting userland proxy: listen udp4 0.0.0.0:51820: bind: address already in use
Error: failed to start containers: wg-easy
```

**Comment by oaltakrouri** [comment]
Turns out I had to run these commands found from a post online:
`sudo service docker stop
sudo rm -f /var/lib/docker/network/files/local-kv.db`
I may have had some residual configuration from an older wireguard container

**Comment by msawatzky75** [comment]
I had a similar issue, a reboot of the system wouldn't allow traffic through the vpn properly, but a quick `docker compose down && docker compose up -d` seemed to do the trick. 

Recreating the docker network database has seemed to remedied this issue, thanks for your research.
