### ISSUE TITLE
Cannot find device "wg0"

### ISSUE THREAD

**Issue by s3rgi** [WeeJeWel/wg-easy#30]
Hi!
When I create the container it gives me this error.
I have docker 20.10 with debian 10 and kernel 4.19.0

Could it be because of the kernel version? 

```
wg-easy    | 2021-06-07T06:20:12.235Z Server Listening on http://0.0.0.0:51821
wg-easy    | 2021-06-07T06:20:12.239Z WireGuard Loading configuration...
wg-easy    | 2021-06-07T06:20:12.244Z WireGuard Configuration loaded.
wg-easy    | 2021-06-07T06:20:12.245Z WireGuard Saving config...
wg-easy    | 2021-06-07T06:20:12.250Z WireGuard Config saved.
wg-easy    | $ wg-quick up wg0
wg-easy    | Error: Command failed: wg-quick up wg0
wg-easy    | Warning: `/etc/wireguard/wg0.conf' is world accessible
wg-easy    | [#] ip link add wg0 type wireguard
wg-easy    | RTNETLINK answers: Not supported
wg-easy    | Unable to access interface: Protocol not supported
wg-easy    | [#] ip link delete dev wg0
wg-easy    | Cannot find device "wg0"
wg-easy    | 
wg-easy    |     at ChildProcess.exithandler (child_process.js:319:12)
wg-easy    |     at ChildProcess.emit (events.js:376:20)
wg-easy    |     at maybeClose (internal/child_process.js:1055:16)
wg-easy    |     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
wg-easy    |   killed: false,
wg-easy    |   code: 1,
wg-easy    |   signal: null,
wg-easy    |   cmd: 'wg-quick up wg0'
wg-easy    | }
wg-easy exited with code 1
```

**Comment by skwiz0d** [comment]
I get this exact same issue.  Clean install no issues on a dietpi instance.  

docker-compose version 1.29.0, build 07737305
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
Docker version 19.03.15, build 99e3ed8919

**Comment by s3rgi** [comment]
In fact it's a problem with the 4.X kernel version. 
Fixed by activating debian backports repos and installing the wireguard dkms package
it works !

**Comment by WeeJeWel** [comment]
Can you make a PR with a note in the readme on how to fix this?

**Comment by yllekz** [comment]
I have the same issue and errror on a  Raspberry Pi 4B and would really appreciate help on what the specific instructions are for "activating debian backports repos and installing the wireguard dkms package"
