### ISSUE TITLE
Routing issue with default config using enumerated interfaces

### ISSUE THREAD

**Issue by Duberry** [WeeJeWel/wg-easy#309]
The config file for wg-easy is hard-coded to eth0. This caused me issues with an install outside of the dockerised environment.

I suggest that a configuration option for the Ethernet adapted is added to allow for a different interface from eth0.

**Comment by WeeJeWel** [comment]
Installing outside Docker.. well, then you're on your own :)

**Comment by alexmo1997** [comment]
Well firstly, even if it's only for non-container environments, why not just add the option?
Also I had the same problem even in a container environment, so this is indeed a problem anyways.
