### ISSUE TITLE
Need to change the UDP port

### ISSUE THREAD

**Issue by Genesis-Fire** [WeeJeWel/wg-easy#311]
The default public UDP port is easy to suffer DDOS. So is it possible to get UDP port changed?

**Comment by Minvinea** [comment]
Hi, yes it's possible.
You can change this port on your docker run command, with this arg "-p 51820:51820/udp" change le port at left with your custom port to expose.

**Comment by Genesis-Fire** [comment]
Hi there, I did try to change the port with the arg "-p my custom port:51820/UDP", but it still stays 51820 after running the docker. That really confused me... > Hi, yes it's possible.
> 
> You can change this port on your docker run command, with this arg "-p 51820:51820/udp" change le port at left with your custom port to expose.

**Comment by platinumthinker** [comment]
> Hi there, I did try to change the port with the arg "-p my custom port:51820/UDP", but it still stays 51820 after running the docker. That really confused me... > Hi, yes it's possible.
> 
> > You can change this port on your docker run command, with this arg "-p 51820:51820/udp" change le port at left with your custom port to expose.

For example if u need change port on 2020 u can run docker with "-p 2020:51820/udp". It mean that docker open 2020/udp port on you host and forward this traffic in docker on 51820 port. Port on you host in private local network not available directly

**Comment by Genesis-Fire** [comment]
Thanks for your answer. So how to make it available? I found once I change the UDP port with the arg "-p 2020:51820/udp", the client I created can't receive any data. So I have to keep the default udp port(51820) to make it work. > > Hi there, I did try to change the port with the arg "-p my custom port:51820/UDP", but it still stays 51820 after running the docker. That really confused me... > Hi, yes it's possible.
> 
> > 
> 
> > > You can change this port on your docker run command, with this arg "-p 51820:51820/udp" change le port at left with your custom port to expose.
> 
> 
> 
> For example if u need change port on 2020 u can run docker with "-p 2020:51820/udp". It mean that docker open 2020/udp port on you host and forward this traffic in docker on 51820 port. Port on you host in private local network not available directly

**Comment by Genesis-Fire** [comment]
> > Hi there, I did try to change the port with the arg "-p my custom port:51820/UDP", but it still stays 51820 after running the docker. That really confused me... > Hi, yes it's possible.
> 
> > 
> 
> > > You can change this port on your docker run command, with this arg "-p 51820:51820/udp" change le port at left with your custom port to expose.
> 
> 
> 
> For example if u need change port on 2020 u can run docker with "-p 2020:51820/udp". It mean that docker open 2020/udp port on you host and forward this traffic in docker on 51820 port. Port on you host in private local network not available directly

Thanks for your answer. So how to make it available? I found once I change the UDP port with the arg "-p 2020:51820/udp", the client I created can't receive any data. So I have to keep the default udp port(51820) to make it work.

**Comment by Genesis-Fire** [comment]
Just notice it says "If you change WG_PORT, make sure to also change the exposed port." So what's the exposed port and how to change it?

**Comment by saschazone35** [comment]
> Just notice it says "If you change WG_PORT, make sure to also change the exposed port." So what's the exposed port and how to change it?

I am also not 100% sure about this, is this "exposed port" refering to -p PORT:51820/udp ?

**Comment by Minvinea** [comment]
> about

Yes, it's that, "PORT" is your custom or not port to expose
