### ISSUE TITLE
4 different configs but same location on all devices.  

### ISSUE THREAD

**Issue by kpinarci** [WeeJeWel/wg-easy#314]
Hello,
I have created 4 configs for 4 users who live in 4 different localities. As one of the users updates his location
in Google Chrome, all other clients are updated as well, all users in Google Chrome have the
same location, which is pretty stupid. Is this an issue with wg-easy, or what exactly am I doing wrong? I How can I prevent this? 

My docker-compose.yml

version: '3.5'
services:
  wg-easy:
    image: weejewel/wg-easy:7
    container_name: wg-easy
    environment:
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=${HOST}
      - PASSWORD=${UI_PASSWORD}
      - WG_PORT=${WG_EXTERNAL_PORT}
    #  - WG_DEFAULT_ADDRESS=10.8.0.1
      - WG_DEFAULT_DNS=1.1.1.1, 8.8.4.4 # 94.140.14.14
      - WG_ALLOWED_IPS=0.0.0.0/0, ::/0
    #labels:
    # com.centurylinklabs.watchtower.enable: "true"
    volumes:
      - /opt/docker/wg-easy/config:/etc/wireguard
    ports:
      - "${WG_EXTERNAL_PORT}:51820/udp"
      - "51991:51821/tcp"
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

**Comment by WeeJeWel** [comment]
What do you mean with ‘updates his location in google chrome’?

**Comment by kpinarci** [comment]
> What do you mean with ‘updates his location in google chrome’?

I mean, I can see the location from the device in Google Chrome where it is (if Chrome opens a new page and scrolls all the way down, you can see the current location).

Setup:
The wg-easy server is in Germany

Client Nr. 1 iPhone is located in Germany
Client Nr. 2 iPad is located in Germany
Client Nr. 3 Macbook is located in Germany
Client Nr. 4 Android is located in Turkey 

If client 4 is connected to wg-easy and updates its location in Google Chrome, then all devices will have the same location. My iPhone 
is located in Germany but google Chrome shows me the location in Turkey.

The problem, I get everything listed in Turkish in google search even though I live in Germany.

**Comment by WeeJeWel** [comment]
Maybe Google remembers these settings by IP? I have no idea.
