### ISSUE TITLE
Ipv6 only VPS

### ISSUE THREAD

**Issue by dibu28** [WeeJeWel/wg-easy#316]
Hello.
Can I use ipv6 only VPS for wg-easy?
Can you please tell me how to modify docker settings for it to work?
And will it work with mobile and desktop clients?

**Comment by petefree1** [comment]
Hello, I am also interested in this question. how to set up ipv6 on vps

**Comment by dibu28** [comment]
@petefree1 Some VPS hosters have cheapest ipv6 only plans.
Like here $2.5mo VPS https://www.vultr.com/pricing/
So I wonder if I can use it for WireGuard and wg-easy.

**Comment by WeeJeWel** [comment]
Duplicate of #138
