### ISSUE TITLE
How to recreate server keys?

### ISSUE THREAD

**Issue by saschazone35** [WeeJeWel/wg-easy#318]
Hi,
I suddenly have connection problems from all clients and I would like to reset the server keys: https://serverfault.com/a/1041230

How do I achieve this with this container?

**Comment by Gyarbij** [comment]
Hi @saschazone35, 

Have you tried to delete and then recreate the client from the portal and see if that fixes the issue?

**Comment by saschazone35** [comment]
We fixed the issue, it had nothing to do with wireguard, but the malfunctioning Port Forwarding of a specific range for a Lancom router. Weirdly it worked for some weeks and then suddenly threw problems and only worked for a handful people.

Fixed it by using port forwarding to a port outside of the malfunctioning range.

IT problems...

**Comment by WeeJeWel** [comment]
Next time close your own issue please :)
