### ISSUE TITLE
Make an API

### ISSUE THREAD

**Issue by megoRU** [WeeJeWel/wg-easy#320]
It would be nice if your script had an API for interaction. 
EndPoints:

-- Deleting
-- Add
-- GetQR_CODE
-- GetConfigFile

**Comment by digvalley** [comment]
Second that. 

as a workaround you can get the sid cookie (or it's content) from a POST to "/api/session" (password in the body) and use it to do queries against the api.

https://github.com/WeeJeWel/wg-easy/blob/bc320fbf792e61658b42292c836ba0b03284d02a/src/www/js/api.js

**Comment by WeeJeWel** [comment]
Sure, fork it!

**Comment by digvalley** [comment]
Assume that means you don't like the idea for your repo?
Or are you looking for help?

**Comment by WeeJeWel** [comment]
I don't see the need currently, but feel free to fork it.

However, if someone wants to create an iOS/Android app for example, I'd be happy to assist.

**Comment by digvalley** [comment]
Fair enough :) thanks for clearifying

**Comment by hexclann** [comment]
@digvalley How to get the cookie? when I run the command with wrong password:

```
curl 'http://example.com:51821/api/session' \
  -H 'Accept: */*' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Origin: http://example.com:51821' \
  -H 'Referer: http://example.com:51821/' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.37' \
  --data-raw '{"password":"password123"}' \
  --compressed \
  --insecure
```

I get a response:

```
{"error":"Incorrect Password","stack":"Error: Incorrect Password\n    at /app/lib/Server.js:59:17\n    at /app/lib/Util.js:23:42"}
```

But when I run it with correct password  get no response. 
Sorry this might be silly question

**Comment by digvalley** [comment]
You won't get a json response - so that is not an error. 

You get a `HTTP 204 (no-content)` status.
In the response tho there will be a `Set-Cookie` header of which the contents you want to grab and pass along in a cookie when doing furture requests.

**Comment by hexclann** [comment]
I got the API working but the publickkey I receive from API response is different from what 's there in the config file

From API response:

```
{
  "name": "testProfile",
  "address": "10.8.0.7",
  "privateKey": "OEEHvXzpbzFQkAsJK6kk7ySmYVW/NaPZIYlgko0uVGc=",
  "publicKey": "g2UCr4tGgAyrnoR3eeBNdVEUohkyTIcAW9neabOZmHo=",
  "preSharedKey": "sr1KHL+i57Tl46aO9kez+/Gf3JZm/fFvy6a7iuVwiME=",
  "createdAt": "2022-10-12T05:43:00.061Z",
  "updatedAt": "2022-10-12T05:43:00.061Z",
  "enabled": true
}
```


From testProfile.conf downloaded from GUI

```
[Interface]
PrivateKey = OEEHvXzpbzFQkAsJK6kk7ySmYVW/NaPZIYlgko0uVGc=
Address = 10.8.0.7/24
DNS = 1.1.1.1


[Peer]
PublicKey = v1d2LgDnLHdlfFI/Js4FT+MBtXgamUA9az/X6avK+gU=
PresharedKey = sr1KHL+i57Tl46aO9kez+/Gf3JZm/fFvy6a7iuVwiME=
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
Endpoint = example.com:51820
```

**Comment by megoRU** [comment]
@digvalley  what is the session lifetime (cookie)

**Comment by megoRU** [comment]
I made wrapper for wg-easy: https://github.com/megoRU/wg-easy-wrapper
