### ISSUE TITLE
Changes DNS

### ISSUE THREAD

**Issue by ogienkoS** [WeeJeWel/wg-easy#321]
Hello everyone, I want to change the default DNS to mine, I write: **docker run -e WG_DEFAULT_DNS = 94.140.14.14**

I get an error: **docker: invalid reference format.**
Tell a newbie how to do it right! Thank you in advance!

**Comment by eandersons** [comment]
There should be no spaces around `=`: `docker run --env WG_DEFAULT_DNS=94.140.14.14 ...`.

The section ["Options" in the `README.md`](https://github.com/WeeJeWel/wg-easy#options) has an example on how environment variables should be set.

**Comment by ogienkoS** [comment]
root@:~# docker run --env IMAGE  WG_DEFAULT_DNS=94.140.14.14
docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.

**Comment by ogienkoS** [comment]
Got an error

**Comment by eandersons** [comment]
Is `docker run --env IMAGE WG_DEFAULT_DNS=94.140.14.14` the whole command you tried to run? If so, then it is incomplete as no image is provided. Please see the section ["2. Run WireGuard Easy"](https://github.com/WeeJeWel/wg-easy#2-run-wireguard-easy).

**Comment by ogienkoS** [comment]
So the team looks like this?
docker run -d \
  --name=wg - easy \
  -e WG_HOST=🚨YOUR_SERVER_IP \
  -e PASSWORD=🚨YOUR_ADMIN_PASSWORD \
  **-e WG_DEFAULT_DNS=94.140.14.14**
  -v ~/.wg-easy:/etc/wireguard\
  -p 51820:51820 /udp \
  -p 51821:51821/TCP\
  --cap-add=NET_ADMIN\
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --restart if not stopped \
  weejewel/wg-easy

**Comment by ogienkoS** [comment]
It won't reinstall anything? Settings won't go away?

**Comment by eandersons** [comment]
Wiregurard configuration is stored in a bind-mounted volume (`-v ~/.wg-easy:/etc/wireguard`), so it will not be lost after the WireGuard Easy container is recreated.
