### ISSUE TITLE
Noobish Problem - Config Saving Issue With Portainer

### ISSUE THREAD

**Issue by voyager529** [WeeJeWel/wg-easy#330]
Hello friends!

So, WG-Easy is fantastic! I love this project and this Docker container. I was using Logonbox before, but it was...far less elegant =).

Now, my problem is that I'm not particularly well-versed in Docker, nor am I really using Docker in its greatest potential, so I rely on Portainer to help me do the things I need done, and despite the inelegance, it works pretty well. I give it the container name from Docker Hub, configure its IP configuration and storage, in the case of WG-Easy do a few toggle switches for the network config, and I'm off to the races.

The problem I'm running into is that WG-Easy loses all the client configs when I update the container. "Sounds like you didn't map the volume the way you were supposed to!" That's what I thought, so I took a look at the Docker Hub page to see if the config folder was listed, and sure enough, part of the example Docker Run command is this:
 -v ~/.wg-easy:/etc/wireguard \

So, the task is to map "~/.wg-easy" to the NFS volume I have created expressly for this container to store its config! Easy peasy:

![image](https://user-images.githubusercontent.com/21685927/181414123-9fa772d5-b2bc-4c91-9cce-d5a1f5333cbd.png)

Only, when I go to deploy the container, I get this:

![image](https://user-images.githubusercontent.com/21685927/181414642-d5d11533-b41f-470f-a6a0-a4f4a17cb424.png)

```
Failure
invalid volume specification: 'nfs.wireguard:~/.wg-easy': invalid mount config for type "volume": invalid mount path: '~/.wg-easy' mount path must be absolute

```

And...that's basically the limit of my knowledge, since I don't know where to either alter the config file path as there doesn't seem to be an ENV variable to do so, or how to tell Portainer "do it anyway"...so, thanks for considering my plight.

**Comment by WeeJeWel** [comment]
This is a fantastic issue! Thank you for taking the time to describe your problem.

You're providing the _host_ path ('~/.wg-easy') to portainer. Instead, you should provide the _guest_ path, which is '/etc/wireguard'.

**Comment by voyager529** [comment]
That works! I love the easy ones. Thank you for the solution.
