### ISSUE TITLE
WG_PORT is ignored

### ISSUE THREAD

**Issue by cgmastertecnology** [WeeJeWel/wg-easy#335]
Hi all,
if i try to change default port from 51820 to, for example, 51920, this seems to be ignored and docker is created with default port 51820.

Any suggestion?

thank you

**Comment by zodiacg** [comment]
Wireguard always listens to 51820 inside the container. The WG_PORT is for generating config files. You use docker to map 51820 to WG_PORT (-p parameter), and wg-easy will generate correct config.

**Comment by cgmastertecnology** [comment]
My goal is to map the listening port on host side not inside the container.
So it's not possibile from WG_PORT ?

**Comment by zodiacg** [comment]
> WG_PORT: The public UDP port of your VPN server. WireGuard will always listen on 51820 inside the Docker container.

Use -p parameter to change which port on the host wiregurad is listening to, in your case, you use:

<pre>docker run -d \
  --name=wg-easy \
  -e WG_HOST=🚨YOUR_SERVER_IP \
 <b> -e WG_PORT=51920 \</b>
  -e PASSWORD=🚨YOUR_ADMIN_PASSWORD \
  -v ~/.wg-easy:/etc/wireguard \
 <b> -p 51920:51820/udp</b> \
  -p 51821:51821/tcp \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --restart unless-stopped \
  weejewel/wg-easy</pre>

You still need to set WG_PORT to 51920 or the config file generated by wg-easy will use 51820 which is not the port being listened  on the host.

**Comment by eandersons** [comment]
@lomas969, did you recreate the container after updating `docker-compose.yml`?
`docker compose up --detach` will automatically recreate the container if changes in `docker-compose.yml` are detected.

**Comment by lomas969** [comment]
Hi @eandersons. I did.
I ran "docker compose down" and then "docker compose up -d".
