### ISSUE TITLE
Can't resolve DNS with Unbound

### ISSUE THREAD

**Issue by NeonMinnen** [WeeJeWel/wg-easy#336]
Hello! I'm having an issue resolving DNS with Unbound. I've basically followed this guide, except I'm running WG-easy through Traefik.
https://craighuther.com/2019/05/14/wireguard-setup-and-installation/

Is there anything I should be looking out for? I've allowed Port 53 on the subnet that WG is using. I can dig google.com on the server and get resolution through 127.0.0.1#53, but if i nslookup on the subnet 10.69.69.1, I get nothing.

Would love some help.

Cheers!

**Comment by xyhhx** [comment]
> but if i nslookup on the subnet 10.69.69.1

Nice

This all looks very familiar tho

![image](https://user-images.githubusercontent.com/105510262/182956211-66edda86-1a20-42e5-aeda-c63fd18b301f.png)
