### ISSUE TITLE
Nginx docker daemon crashes shortly after docker-compose up

### ISSUE THREAD

**Issue by WeaverOfTheWeb** [WeeJeWel/wg-easy#349]
I'm using the nginx-certbot setup mentioned in the docs https://github.com/WeeJeWel/wg-easy/wiki/Using-WireGuard-Easy-with-nginx-SSL but as soon as the daemon boots up it crashes. Any idea what's happening or why?

**Comment by WeeJeWel** [comment]
Not without any logs of course :)

**Comment by WeaverOfTheWeb** [comment]
Thanks for the quick reply @WeeJeWel! I realised what my problem was, I was missing the `hostname: wg-easy` property 😅
