### ISSUE TITLE
Wireguard configuration does not work with Windwos 10 laptop

### ISSUE THREAD

**Issue by FedericoCoppola97** [WeeJeWel/wg-easy#350]
Hello,
I deployed "wg-easy" docker in my home network and I created my first WireGuard VPN user for my mobile with success (I used QR Code option).
After that I created another user for my Windows 10 laptop. I downloaded VPN configuration file, so I imported this configuration file in Win10 Wireguard client.

The VPN does not work fine, so I get this error:
2022-08-16 17:10:08.117: [TUN] [Home] Handshake for peer 1 (my_public_ip:6666) did not complete after 5 seconds, retrying (try 2)
2022-08-16 17:08:57.174: [TUN] [Home] Sending handshake initiation to peer 1 (my_public_ip:6666)

I can use Wireguard without issue with my Android mobile phone.

Have you got some suggestions for me?

**Comment by sp0ker** [comment]
Hi Federico
To be sure this is not a firewall issue somewhere on your network, can you verify you can telnet your wireguard server ?

`telnet publicip:wireguardport`

**Comment by WeeJeWel** [comment]
Probably not an issue with wg-easy.
