### ISSUE TITLE
WG_DEFAULT_DNS is ignored

### ISSUE THREAD

**Issue by Genesis-Fire** [WeeJeWel/wg-easy#354]
Hi there, I would like to add 2 SmartDNS by running below, but ONLY DNS2 displays in my peer config. Please kindly advise.

docker run -d \
  --name=wg-easy \
  -e WG_HOST=IP \
  -e PASSWORD=PASSWORD \
  -e WG_DEFAULT_DNS=DNS1 \
  -e WG_DEFAULT_DNS=DNS2 \
  -v ~/.wg-easy:/etc/wireguard \
  -p 51820:51820/udp \
  -p 51821:51821/tcp \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --restart unless-stopped \
  weejewel/wg-easy

**Comment by grayguest** [comment]
-e WG_DEFAULT_DNS=DNS1,DNS2

**Comment by Genesis-Fire** [comment]
> -e WG_DEFAULT_DNS=DNS1,DNS2

Thanks for your reply. I did try this, but this fail to run the command.

**Comment by grayguest** [comment]
what does it tips?

**Comment by Genesis-Fire** [comment]
> what does it tips?

The error says "Unable to find image 'MY IP:latest' locally
docker: Error response from daemon: pull access denied for DNS2, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'."

**Comment by eandersons** [comment]
@Genesis-Fire , seems that you have placed a space between comma and the second DNS, causing the command `docker run` interpret the second DNS as an image name (see the [`docker run`](https://docs.docker.com/engine/reference/run/) signature: `docker run [OPTIONS] IMAGE[:TAG|@DIGEST] [COMMAND] [ARG...]`).
You could try to enclose the value in quotes or remove the space. Like so: `-e WG_DEFAULT_DNS='8.8.8.8, 8.8.4.4'` or `-e WG_DEFAULT_DNS=8.8.8.8,8.8.4.4`.

**Comment by Genesis-Fire** [comment]
> @Genesis-Fire , seems that you have placed a space between comma and the second DNS, causing the command `docker run` interpret the second DNS as an image name (see the [`docker run`](https://docs.docker.com/engine/reference/run/) signature: `docker run [OPTIONS] IMAGE[:TAG|@DIGEST] [COMMAND] [ARG...]`). You could try to enclose the value in quotes or remove the space. Like so: `-e WG_DEFAULT_DNS='8.8.8.8, 8.8.4.4'` or `-e WG_DEFAULT_DNS=8.8.8.8,8.8.4.4`.

Woah, it did works after removing the space between comma and the DNS2. Appreciate your advise. I thought it should be a space between previously.
