### ISSUE TITLE
No access to SMB

### ISSUE THREAD

**Issue by ferby09** [WeeJeWel/wg-easy#368]
Hey there,
I'm using wg-easy as a docker in unRAID and I'm able to connect with my Android phone. However, I can't connect to my Samba shares in my file explorer app. It used to work when I was installing the docker some months ago iirc. At least it worked with OpenVPN.
The IP range is 192.168.178.1. I tried adding it in WG_ALLOWED_IPS = 192.168.178.0/24, 10.8.0.0/24 but that didn't work. Interestingly enough my client (Android) shows 0.0.0.0/0, ::/0 as allowed ips. That is the default iirc. So could it be that the variable is ignored in my docker?
Is this even the right approach to solve this issue?
Thank you very much in advance!

**Comment by eandersons** [comment]
Setting/changing value for `WG_ALLOWED_IPS` will not change allowed IPs for existing clients. This value will only be available in newly generated client configurations.
In existing clients allowed IPs should be changed manually.

**Comment by ferby09** [comment]
Yeah, I already thought about that but didn't try. You're right, it shows the allowed ips correctly now. It still doesn't work nevertheless. When I'm in my local wifi and using the VPN I can access my smb shares but with mobile network it won't connect. But accessing local sites like unRAID in my browser works with mobile data.

**Comment by ferby09** [comment]
What else can I do to troubleshoot the problem?

**Comment by ferby09** [comment]
I was too stupid to find the build-in Wireguard in unRAID.
Using this works now.
