### ISSUE TITLE
Incorrect password

### ISSUE THREAD

**Issue by whytf** [WeeJeWel/wg-easy#377]
Defined password even when copied does not work.

**To Reproduce**
1. Create docker-compose.yml from example
2. Customize & change password
3. Password never works

**Expected behavior**
Password would work.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version 105.0.5195.102
 - 
**Additional context**
docker-compose.yml:

`
version: "3"
services:
  wg-easy:
    environment:
      # Required:
      # Change this to your host's public address
      - WG_HOST=x.x.x.x

      # Optional:
      - PASSWORD="xxxxxxxxx"
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=192.168.0.2
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt

    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - .:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1`

**Comment by eandersons** [comment]
I suspect that your password contains the character `$`. If that is the case, then symbols behind `$` are interpreted as an environment variable when a string is enclosed in double quotes because of [shell parameter expansion](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html). For example, `"abc$dq3-dsr"` would result in `abc-dsr` as most probably the environment variable `dq3` is not defined.
Solution is to use single quotes or no quotes at all, or escape `$` (`\$`).

**Comment by seikosantana** [comment]
I'm having the same issue with instructions in the readme

**Comment by whytf** [comment]
> I suspect that your password contains the character `$`. If that is the case, then symbols behind `$` are interpreted as an environment variable when a string is enclosed in double quotes because of [shell parameter expansion](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html). For example, `"abc$dq3-dsr"` would result in `abc-dsr` as most probably the environment variable `dq3` is not defined. Solution is to use single quotes or no quotes at all, or escape `$` (`\$`).

This was actually the problem.
