### ISSUE TITLE
Make the "active" icon green

### ISSUE THREAD

**Issue by haldi4803** [WeeJeWel/wg-easy#383]
Sup,

Nice tool.
But seriously... i can see why you have a decent color scheme... but the pulsing active button should be green in any case...
![image](https://user-images.githubusercontent.com/17104473/191587104-57b52926-d369-4dba-a906-1a44b3f42efc.png)

At first i was like "wait what? red button? connection refused?"

**Comment by WeeJeWel** [comment]
Sure, make a PR and show me a better way :)
