### ISSUE TITLE
Error running WireGuard Easy with Pi-hole

### ISSUE THREAD

**Issue by lrkrol** [WeeJeWel/wg-easy#386]
**Describe the bug**
When using the [provided `docker-compose.yml` script to install WireGuard Easy along Pi-hole](https://github.com/WeeJeWel/wg-easy/wiki/Using-WireGuard-Easy-with-Pi-Hole), the following errors occurs:
```
wg-easy is up-to-date
Starting pihole ...
Starting pihole ... error

ERROR: for pihole  Cannot start service pihole: driver failed programming external connectivity on endpoint pihole (ca344214a70b329978b161bedb7cdd4828c78a6a6287428b0f56a3cf74581770): Error starting userland proxy: listen tcp4 0.0.0.0:53: bind: address already in use

ERROR: for pihole  Cannot start service pihole: driver failed programming external connectivity on endpoint pihole (ca344214a70b329978b161bedb7cdd4828c78a6a6287428b0f56a3cf74581770): Error starting userland proxy: listen tcp4 0.0.0.0:53: bind: address already in use
```
The above pasted output is after a re-run of the file; the initial run does two things at the same time, messing up the output a bit. Screenshot below.

WireGuard Easy does install and has its UI up and running at port 51821; Pi-hole does not.

**To Reproduce**
1. I was using a clean install of Ubuntu running on a VPS.
```
                          ./+o+-       root@
                  yyyyy- -yyyyyy+      OS: Ubuntu 22.04 jammy
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 5.15.0-47-generic
           .++ .:/++++++/-.+sss/`      Uptime: 13m
         .:++o:  /++++++++/:--:/-      Packages: 647
        o:+o+:++.`..```.-/oo+++++/     Shell: bash 5.1.16
       .:+o:+o/.          `+sssoo+/    Disk: 6.1G / 25G (26%)
  .++/+:+oo+o:`             /sssooo.   CPU: QEMU Virtual version 2.5+ @ 2.845GHz
 /+++//+:`oo+o               /::--:.   GPU: Cirrus Logic GD 5446
 \+/+o+++`o++o               ++////.   RAM: 383MiB / 969MiB
```
2. I used the [provided `docker-compose.yml` to install WireGuard Easy along Pi-hole](https://github.com/WeeJeWel/wg-easy/wiki/Using-WireGuard-Easy-with-Pi-Hole), i.e., I created the file, then first needed to run `apt install docker-compose`, and then ran `docker-compose up -d`. 

**Expected behavior**
Script runs through, installs wg-easy and pihole.

**Screenshots**
![image](https://user-images.githubusercontent.com/29232182/192298411-29ad4007-6c00-4a4b-9a62-10f051384aff.png)

**Comment by lrkrol** [comment]
Apparently the issue is caused by systemd-resolve listening on port 53. I followed [these steps](https://web.archive.org/web/20220612212822/https://www.bklynit.net/ubuntu-20-04-lts-docker-pihole/), and the issue was resolved. Still, is this something the script could take into account automatically?

**Comment by eandersons** [comment]
With "script" are you referring to `docker-compose.yml`? If so, [compose file](https://docs.docker.com/compose/compose-file/#compose-file) is not a script so it cannot change host's configuration, and user is responsible to make sure that mapped host ports (value before `:` in [`ports`](https://docs.docker.com/compose/compose-file/#ports)) are not used.

**Comment by lrkrol** [comment]
Thanks for the response; I understand. To the extent that this is now standard behaviour on current Ubuntu distributions (which I am not sure of), it may nonetheless be worthwhile to make mention of it. Either way, I see it is nothing to do with wg-easy specifically.
