### ISSUE TITLE
How to setup roadwarrior style VPN with wg-easy?

### ISSUE THREAD

**Issue by smshr** [WeeJeWel/wg-easy#4]
Thank-you for this project. I have yet to successfully run and test this, pending issues mentioned in #3.
I am trying to run a roadwarrior style vpn, will it be possible to run it using wg-easy, would I need to make any config changes or it will run roadwarrior style vpn from the get go.

I hope to be able to access hosts and services (like smb, nfs, printer, etc) running in my home network from the connected vpn client device.

**Comment by WeeJeWel** [comment]
I have no idea what roadwarrior-style means.

**Comment by smshr** [comment]
Road Warriors are remote users who need secure access to the home or workplace infrastructure. I guess this term is mostly used in US.
Basically, roadwarrior style vpn is like workplace vpn, where you can access network infrastructure as opposed to the commercial vpn-services which are internet only.

In case of roadwarrior wireguard running in container, it should extend or allow access to the home/work network, not docker/kubernetes network.

**Comment by WeeJeWel** [comment]
I see. This project can work for exactly that purpose, as long as you run it _inside_ your LAN.

**Comment by cb3inco** [comment]
@smshr - Wireguard does this very well. I use WG for primary access to two data centers instead of using my firewall VPN. Much more reliable and I can be on one network, suspend my computer, go to another network and be reconnected in seconds.
