### ISSUE TITLE
wg-easy install error with iptables

### ISSUE THREAD

**Issue by byKeksYT** [WeeJeWel/wg-easy#405]
**Describe the bug**
When I try to install wg-easy on my KVM with Debian 11 I get the following error message: 
```
docker: Error response from daemon: driver failed programming external connectivity on endpoint wg-easy (08bd87ff8f17308341215b1e3c9ec5ea469e6d13d87700c8f99ac8c5e02d394e):  (iptables failed: iptables --wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.2 --dport 51821 -j ACCEPT: iptables: No chain/target/match by that name.
 (exit status 1)).
```

**Screenshot**
![Screenshot of the CLI](https://verstandlxs.eu/static/wgeasy-iptables-problem-screenshot.png)

**Expected behavior**
The wireguard install to happen successfully

**Comment by Czocher** [comment]
Try to restart docker:
```
sudo systemctl restart docker
```
If that doesn't help, clear the `iptables` chains and restart `docker` again:
```
sudo iptables -t filter -F
sudo iptables -t filter -X
sudo systemctl restart docker
```

**Comment by byKeksYT** [comment]
Hey, thanks for the help, now my wg-easy is working. Can you also tell me, which IP or IP ranges I have Go release in my firewall? Currently I have no access to the internet while I am connected to my WireGuard, most likely because my firewall is blocking it.

**Comment by Czocher** [comment]
In reality if you have ip forward enabled on your system it should run out-of-the-box. Verify it with:
```
sudo cat /proc/sys/net/ipv4/ip_forward
```
The command above should return `1`. If that's not the case, then perform:
```
sysctl -w net.ipv4.ip_forward=1
```
to enable it.


The system on which docker is configured should perform network address translation (NAT) and any external firewall should not even see those connections as remote - they should look as if your server performed them for any external observer including external firewalls.

If the firewall is on the docker host then configure it to allow any outgoing connections:
```
sudo iptables -I OUTPUT -j ACCEPT
```

Also verify if the routing provided by `wg-easy` and there is a route from the container to your external network:
```
sudo ip route
```
(Note that the `ip route` check should be done **on the container** not on the docker-host).

You can also check if your docker-host firewall accepts all connections coming from the internal docker network.
