### ISSUE TITLE
Consider an OSI-approved license

### ISSUE THREAD

**Issue by principis** [WeeJeWel/wg-easy#42]
wg-easy is currently not licensed which makes it proprietary. Please consider licensing it under an [https://opensource.org/licenses/category](OSI-approved) license. This would make it easier for others to contribute to the project or use it.

**Comment by wilfrieddaniels** [comment]
Agreed, having no license makes the project proprietary and technically illegal to modify for contributors. Please fix!

**Comment by WeeJeWel** [comment]
Well, it's not OSI, but should cover everything that's important: https://github.com/WeeJeWel/wg-easy/blob/master/LICENSE.md

**Comment by principis** [comment]
I always recommend using an OSI-approved license because it would make the software open-source. I understand your point of view that you don't want someone to sell it, but the license remains very vague. Restrictive copy-left licenses help protect the project from being sold as a commercial product. (For example the AGPL).

Anyway, I don't want to sell anything, just make some changes, so I think it is fine. Thank you.
