### ISSUE TITLE
How to login?

### ISSUE THREAD

**Issue by Fastidious** [WeeJeWel/wg-easy#45]
I am running the application with `node server.js`. I have set the password on the `config.js` file like so:

```
module.exports.PASSWORD = process.env.PASSWORD || 'password';
```

When I go to the page, I keep getting the modal window stating "Not Logged In," but no prompt for password shows. What am I doing wrong?

**Comment by WeeJeWel** [comment]
Sorry, but I can't reproduce. Please share a screencast of your issue.

**Comment by Fastidious** [comment]
Sure. This is what I see after adding the PASSWORD environmental variable, restarting the application, and reloading the page:

https://user-images.githubusercontent.com/8352292/126040311-8051dfdc-5c00-4a87-815b-64480f2cd96a.mov

**Comment by WeeJeWel** [comment]
Unfortunately I cannot reproduce your issue (Safari, macOS 11).

You should set the password using `docker-compose.yml` by the way. Shouldn't make a difference though.
