### ISSUE TITLE
Lost password of the webgui. what to do?

### ISSUE THREAD

**Issue by Klagio** [WeeJeWel/wg-easy#477]
I can't remember my password, is there a way to gain access to the configuration file and look at it?

I installed wg-easy with docker in synology nas. Not very familiar with docker, I wnet inside, but can't find the file .wg-easy

**Comment by steinauf85** [comment]
the . in front of .wg-easy indicates that it's hidden. it should be in the home folder unless you moved it elsewhere.

**Comment by Klagio** [comment]
> the . in front of .wg-easy indicates that it's hidden. it should be in the home folder unless you moved it elsewhere.

thanks I am having trouble to find it. I do login with putty or winscp, after that how and where to look for the file?

**Comment by Klagio** [comment]
I used docker run command. At home I have Synology, but that's fine, this second I have in office on a Ubuntu 20.04 server VM.

My problem is in the office. How to do?

**Comment by steinauf85** [comment]
Just type in the command I mentioned from the console or ssh session on
whichever computer you need. It’ll tell you the answer to your question
(what you used as the env variable from the running container).

**Comment by ogienkoS** [comment]
> ah yeah, those config files are for wireguard, not for the docker container. How did you start your container? using docker run command or docker-compose.yml? If using docker-compose, then you just need to find that YAML file
> 
> If Docker in the Synology has an inspect tool, you can use that and lookup Config.Env. Otherwise, from the console you can enter: `docker inspect -f "{{index (index .Config.Env) 0 }}" wg-easy`. If you want to see all of your variables, then use `docker inspect -f "{{ .Config.Env }}" wg-easy`. May needs to put sudo in front depending on how your permissions are set.
> 
> the other option is you can kill your container and start it up again using a new password. Since your data should be stored in the persistent volumes, you wont lose anything in the process

Hello, can I change the password on the web panel using some command without reinstalling WG-Easy?

**Comment by WeeJeWel** [comment]
Follow https://github.com/WeeJeWel/wg-easy#updating

**Comment by Klagio** [comment]
> docker inspect -f "{{ .Config.Env }}" wg-easy

perfect!!! Thanks
