### ISSUE TITLE
Web API Documentation

### ISSUE THREAD

**Issue by gaby** [WeeJeWel/wg-easy#48]
Love your dashboard! Is there any documentation on how to use the API for creating/editing/deleting/enabling/deleting clients?

**Comment by WeeJeWel** [comment]
This might suffice: https://github.com/WeeJeWel/wg-easy/blob/master/src/www/js/api.js

**Comment by gaby** [comment]
@WeeJeWel Thank you! :-)

**Comment by MachineSaver** [comment]
Does this define authentication?
Or can someone give me some pointers on how to authenticate myself when connecting to my wg-easy instance?

**Comment by igorshirinkin** [comment]
@MachineSaver change api url var, like 
```python
api_url = 'http://0.0.0.0:9999/api/'
```
