### ISSUE TITLE
Allowed IPs variable doesn't pass into the container

### ISSUE THREAD

**Issue by Zaelnorth** [WeeJeWel/wg-easy#494]
**Describe the bug**
When starting the container, the following argument was passed: 

> -e 'WG_ALLOWED_IPS '='192.168.0.0/24, 10.8.0.0/24'

Unfortunately the default conf files contain the following:

> AllowedIPs = 0.0.0.0/0, ::/0

_

**To Reproduce**
1. Pass WF_ALLOWED_IPS to the container
2. See if this argument made it to the conf files for individual clients

**Expected behavior**
The arguments should pass into the conf files.

**Desktop (please complete the following information):**
 - OS: Unraid
 - Browser: Chrome
 - Version Installed 19/2/23, tag: latest

**Comment by MacArthurL** [comment]
Hi, do not use '' in the code, it should be write like
-e WG_ALLOWED_IPS=192.168.0.0/24,10.8.0.0/24 \

**Comment by Zaelnorth** [comment]
@MacArthurL thanks for this, the culprit wasn't the " but the extra space after the IPS, after removing it, it worked, thank you!
