### ISSUE TITLE
My container restarts in a loop

### ISSUE THREAD

**Issue by Minvinea** [WeeJeWel/wg-easy#50]
Hi,
I seen your project this week, it's very great.
Today, I have try to use your project but I have a problem.
I have follow your steps, but I start my container with (docker-compose up --detach) and after the container reboot in loop.
<a href="https://ibb.co/wN0H273"><img src="https://i.ibb.co/Y7R9VXY/Capture-d-cran-du-2021-08-15-18-15-27.png" alt="Capture-d-cran-du-2021-08-15-18-15-27" border="0"></a>

Here my config :
<a href="https://imgbb.com/"><img src="https://i.ibb.co/0JBY7j8/Capture-d-cran-du-2021-08-15-18-16-03.png" alt="Capture-d-cran-du-2021-08-15-18-16-03" border="0"></a>

Here is my system informations :
- Debian 10.10 : Linux Debian 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux
- Docker : Docker version 20.10.8, build 3967b7d
- Docker-compose : docker-compose version 1.29.2, build 5becea4c

If you have a idea or a solve, i want.

Thanks !

**Comment by williamkennyAK** [comment]
What is the output when you run:  docker logs wg-easy

**Comment by Minvinea** [comment]
> 
> 
> What is the output when you run: docker logs wg-easy

Hi, this is my output :

`2021-08-17T17:36:30.751Z Server Listening on http://0.0.0.0:51821
2021-08-17T17:36:30.752Z WireGuard Loading configuration...
2021-08-17T17:36:30.755Z WireGuard Configuration loaded.
2021-08-17T17:36:30.756Z WireGuard Saving config...
2021-08-17T17:36:30.760Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: Command failed: wg-quick up wg0
Warning: `/etc/wireguard/wg0.conf' is world accessible
[#] ip link add wg0 type wireguard
RTNETLINK answers: Not supported
Unable to access interface: Protocol not supported
[#] ip link delete dev wg0
Cannot find device "wg0"

    at ChildProcess.exithandler (child_process.js:390:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'wg-quick up wg0'
}
`

**Comment by williamkennyAK** [comment]
What kernel version are you running?  If your kernel dies not support wireguard natively (5.6 and above) it will not work.

**Comment by squadramunter** [comment]
@Minvinea I got the same thing. You need to install Wireguard. This is not included in the docker container sadly.

For me it worked when I installed it by the follwing way.

https://www.cyberciti.biz/faq/debian-10-set-up-wireguard-vpn-server/

Follow Step1, Step2 and Step3.

Then it should work as expected. Got the same problem as you and this worked for me.

**Comment by Minvinea** [comment]
> 
> 
> What kernel version are you running? If your kernel does not support wireguard natively (5.6 and above) it will not work.

Yes, my Debian 10.10 use this version of kernel : 
![image](https://user-images.githubusercontent.com/29579830/130360138-1eacb20a-e6c8-4263-a3b0-1b3f73c3e339.png)

**Comment by Minvinea** [comment]
> 
> 
> @Minvinea I got the same thing. You need to install Wireguard. This is not included in the docker container sadly.
> 
> For me it worked when I installed it by the follwing way.
> 
> https://www.cyberciti.biz/faq/debian-10-set-up-wireguard-vpn-server/
> 
> Follow Step1, Step2 and Step3.
> 
> Then it should work as expected. Got the same problem as you and this worked for me.

Hi, @squadramunter 
I'm a noob with docker. I should install wireguard on my server or in mine container?
If it's in my serveur i'ts okay i can but i'ts in mine container i dont know make that.
You can help me ? or explain the setps.

**Comment by williamkennyAK** [comment]
You should install wireguard directly on your Debian 10 server.  I would also recommend upgrading to Debian 11 if feasible.  If not, follow steps 1-3 in the link that @squadramunter provided on your host system then spin up the wg-easy container you should be all set.

**Comment by squadramunter** [comment]
And make sure you enable the backports repository so the wireguard module does install well on your Debian 10 host. Just follow the instructions I send you.

**Comment by Minvinea** [comment]
Thanks @williamkennyAK and @squadramunter it's works ! Have a good day !

**Comment by WeeJeWel** [comment]
I suggest to start a GitHub Wiki with installation instructions for popular, non-recent host platforms without WireGuard kernel support.

**Comment by Minvinea** [comment]
> 
> 
> I suggest to start a GitHub Wiki with installation instructions for popular, non-recent host platforms without WireGuard kernel support.

Yes, it's a good idea
