### ISSUE TITLE
wg-easy container doesn't start

### ISSUE THREAD

**Issue by valyrian84** [WeeJeWel/wg-easy#501]
I have been trying to get the container spun-up but it executes the spin-up but then exits with the error.

**Command** -
`sudo docker run -d -p 51820:51820/udp -p 51821:51821/tcp --name=wg-easy -e WG_HOST=mypublicdns.com -e PASSWORD=MyPassword -v /srv/zdrive/Appdata/wireguard weejewel/wg-easy:latest --cap-add=NET_ADMIN --cap-add=SYS_MODULE --sysctls="net.ipv4.conf.all.src_valid_mark=1" --sysctl=net.ipv4.ip_forward=1 --restart unless-stopped`

Error -
```
node: bad option: --cap-add=NET_ADMIN
node: bad option: --cap-add=SYS_MODULE
node: bad option: --sysctl=net.ipv4.conf.all.src_valid_mark=1
node: bad option: --sysctl=net.ipv4.ip_forward=1
node: bad option: --restart
```

**Comment by eandersons** [comment]
Your `docker run` command is invalid because the image has to be specified after options.
Take a closer look at [WireGuard Easy documentation](/WeeJeWel/wg-easy#2-run-wireguard-easy) and [`docker run` reference](https://docs.docker.com/engine/reference/run/).

**Comment by valyrian84** [comment]
@eandersons Thanks for pointing the error. I am able to start the container now and successfully connect to in remotely. Thanks a bunch.
