### ISSUE TITLE
wg-easy working, but can't ssh or ping local ip?

### ISSUE THREAD

**Issue by MasterKryszn** [WeeJeWel/wg-easy#503]
**Describe the bug**
Can connect to wg-server without issue, my traffic is routing through local DNS, but cannot ssh into local network servers via ip or hostname

**Comment by armdan** [comment]
same here

**Comment by MasterKryszn** [comment]
> same here

are you using Termius app by any chance?

In my case, SSH does work but for some reason not with Termius. When I use alternative app to ssh, no problem. So, not sure if this is Termius issue or a wg-easy not working with Termius issue?

**Comment by armdan** [comment]
no, I don't. I am able to connect but I can't access any devices on the network

**Comment by MasterKryszn** [comment]
Apparently was issue with using Termius via Samsung secure apps
