### ISSUE TITLE
how is wg-easy going to be affected by Docker dropping "free team accounts" ?

### ISSUE THREAD

**Issue by bmullan** [WeeJeWel/wg-easy#513]
**[Docker announces the end of Docker Free Teams.](https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/
)**

**Comment by 0x6DD8** [comment]
> Will open source images I rely on get deleted?
Not by Docker. Public images will only disappear if the maintainer of the image decides to proactively delete it from Docker Hub. If the maintainer takes no action, we will continue to distribute their public images. (Of course, if the maintainer migrates to the Docker-Sponsored Open Source program or to a paid Docker subscription, we will also continue to distribute their public images.)

it affects only people who use **private repositories**

**Comment by choque88** [comment]
And as of March 24, 2023, Docker has reversed its decision to sunset the “Docker Free Team” plan.
