### ISSUE TITLE
gui password not deleted after logout

### ISSUE THREAD

**Issue by sgiannulli** [WeeJeWel/wg-easy#52]
Hi,
just added this new docker on my machine and noticed that when you log out from the web gui the password is not cancelled; this could be considered a security problem. 
I noticed this with firefox 91.0.1 on win10.
![immagine](https://user-images.githubusercontent.com/14077090/129972377-d60948c7-e609-4915-88e5-67a84abd2a02.png)

**Comment by gaby** [comment]
@sgiannulli Usually the browser is the one saving that. Check your settings to see if by default your browser is saving credentials.

**Comment by gaby** [comment]
I can confirm, that I have the same issue.

**Comment by Ravinou** [comment]
I have the same issue.
