### ISSUE TITLE
Ubuntu no internet connection

### ISSUE THREAD

**Issue by igorshirinkin** [WeeJeWel/wg-easy#524]
Hi!
I have an error when using wireguard from my computer. I installed the docker container on DigitalOcean according to the documentation. After installation went to the GUI and created two users. For my iphone and the other for my pc. The pc has OS Ubuntu 22.04 installed. When I try to connect to the network via the `wg-quick up wg0` command I get internet disconnected. If I try to ping the server through the tunnel, my pc sees it and gives packets, but no internet access.
At the same time my iPhone connects to the internet without any problems and works with wireguard

![2023-04-05_18-23](https://user-images.githubusercontent.com/57989248/230094650-d5e82e3f-552c-41c9-8cef-d821e2f9ade2.png)
![2023-04-05_18-24](https://user-images.githubusercontent.com/57989248/230094657-316beea8-1589-41fb-8999-988e621ab834.png)
![2023-04-05_18-25](https://user-images.githubusercontent.com/57989248/230094661-086b8fcd-ef3e-43ef-b8f3-c353b4e0aa07.png)
![2023-04-05_18-28](https://user-images.githubusercontent.com/57989248/230095104-b1f7481f-0b30-4595-8199-39e77070c926.png)

**Comment by Pleonazm** [comment]
Do you want ALL your traffic go via your WG Server?

What's the output of "ip route" command on your Ubuntu?

**Comment by igorshirinkin** [comment]
Ну да. Если запускаю WG, то я хотел бы заходить на сайты, которые не доступны в Российской федерации.

Вот мой `ip route`
![2023-04-05_18-41](https://user-images.githubusercontent.com/57989248/230099161-a6c57b77-ea36-4c70-8317-5539727e11c4.png)

**Comment by Pleonazm** [comment]
Your Default Gateway is not by your Wireguard interface. try changing Allowed IPs to:
0.0.0.0/1, 128.0.0.0/1
You then have two more specific (I.e. always preferable) routes (instead of one default route) covering all IPs address space.

**Comment by igorshirinkin** [comment]
Your first recommendation didn't work, but I returned the second path `::/0` and I was able to go to github! But google/youtube and others still doesn't work :)

A
![2023-04-05_19-12](https://user-images.githubusercontent.com/57989248/230108425-3dd9599d-8cc4-4e22-8597-11be75a4acfc.png)
ny other ideas?

**Comment by igorshirinkin** [comment]
@Pleonazm The pages were cached, so they worked. My bad..sorry for the misinformation

**Comment by Regis-Loyaute** [comment]
here is my docker-compose if that can help

version: "3.8"

services:
wg-easy:
environment:
- WG_HOST=your ip
- PASSWORD=your password
- WG_DEFAULT_DNS=10.100.1.254
# - WG_PORT=51820
# - WG_DEFAULT_ADDRESS=10.8.0.x
# - WG_MTU=1420
- WG_ALLOWED_IPS=192.168.0.0/16, 10.0.0.0/8
image: weejewel/wg-easy
container_name: wg-easy
volumes:
- ./data:/etc/wireguard
ports:
- "51820:51820/udp"
- "51821:51821/tcp"
restart: unless-stopped
cap_add:
- NET_ADMIN
- SYS_MODULE
sysctls:
- net.ipv4.ip_forward=1
- net.ipv4.conf.all.src_valid_mark=1

**Comment by igorshirinkin** [comment]
@Regis-Loyaute 
Thanks for the answer, but I still can't connect to the internet with these settings

**Comment by igorshirinkin** [comment]
I installed a clean version of Ubuntu on my virtual machine and went through all the steps to install Wireguard. I have disabled the firewall and the ports are free, but I still can't connect to the internet.
I also tried installing Windows 11 on my virtual machine and wireguard tunnel works fine on it

**Comment by igorshirinkin** [comment]
Any ideas? Why my system block traffic?

**Comment by Regis-Loyaute** [comment]
> Any ideas? Why my system block traffic?

Have you done a port forwarding on your firewall ? ...

**Comment by igorshirinkin** [comment]
My ufw firewall is inactive

**Comment by Regis-Loyaute** [comment]
I meant on the box that your ISP provided ?

**Comment by Regis-Loyaute** [comment]
Oh wait you are able to reach your wireguard firewall but not within the subnet ? have you change this parameter to this your internal network on your docker compose WG_ALLOWED_IPS=

**Comment by igorshirinkin** [comment]
![2023-04-21_11-49](https://user-images.githubusercontent.com/57989248/233562001-0c0b61e3-6617-4a86-92d2-1589953682f3.png)

**Comment by igorshirinkin** [comment]
I just installed a clean Debian image and on it the WG works fine :(, but on Ubuntu does not want

**Comment by igorshirinkin** [comment]
Hi @Regis-Loyaute, @Pleonazm. Thanks for your help, the problem was solved by installing Ubuntu 23.04. I do not know what the problem remains on Ubuntu 22.04
