### ISSUE TITLE
Wireguard working but Ad Blocking Isn't

### ISSUE THREAD

**Issue by itsMikeLowrey** [WeeJeWel/wg-easy#529]
**Describe the bug**
I used this guide to install wireguard and pihole.  [guide](https://github.com/WeeJeWel/wg-easy/wiki/Using-WireGuard-Easy-with-Pi-Hole)
**To Reproduce**
Copy & paste the docker-compose.yml from the documentation.
Replace variables with your own.
Disable systemd-resolved.
Start the containers using docker compose up -d
See DNS errorwhen updating block list.

**Expected behavior**
I expect to add blocking to be better. There is no difference in ads when I use the vpn vs not using it. I use this site to test if pihole is working: https://d3ward.github.io/toolz/adblock.html

**Screenshots**
Here is a screenshot of the DNS error it gives me: https://imgur.com/a/b4ZZEzx
**Desktop (please complete the following information):**
Ubuntu 20, chrome browser.
This issue is on desktop, iPad and phone for me. 

I think someone ran into a similar problem here: https://github.com/WeeJeWel/wg-easy/issues/479

**Comment by itsMikeLowrey** [comment]
I ran pihole diagnostics and it isnt giving me any errors. I also updated my block list and it worked well and did not give me any errors. This was after restarting the server. This leads me to think that it is an issue in communication between wg-easy and pihole since both of the systems seem to be working independently.

**Comment by itsMikeLowrey** [comment]
I am now seeing this when I run a diagnostic. It makes me think something is misconfigured. https://imgur.com/a/Nya9njy

**Comment by Regis-Loyaute** [comment]
You need to put your Pihole IP in your docker compose DNS variable, here is mine for example:

version: "3.8"

services:
  wg-easy:
    environment:
      - WG_HOST=your ip
      - PASSWORD=your password
      - WG_DEFAULT_DNS=10.100.1.254
      # - WG_PORT=51820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      # - WG_MTU=1420
      - WG_ALLOWED_IPS=192.168.0.0/16, 10.0.0.0/8
    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - ./data:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

**Comment by itsMikeLowrey** [comment]
thanks for the help! Here is my full yaml:
`version: "3.8"

services:
  wg-easy:
    environment:
      # ⚠️ Change the server's hostname (clients will connect to):
      - WG_HOST=#my vps ip

      # ⚠️ Change the Web UI Password:
      - PASSWORD=foobar123
      - WG_DEFAULT_DNS=10.8.1.3
    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - ~/.wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wg-easy:
        ipv4_address: 10.8.1.2
  pihole:
    image: pihole/pihole
    container_name: pihole
    environment:
      # ⚠️ Change the Web UI Password:
      - WEBPASSWORD=foobar123
    volumes:
      - '~/.pihole/etc-pihole:/etc/pihole'
      - './.pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "5353:80/tcp"
    restart: unless-stopped
    networks:
      wg-easy:
        ipv4_address: 10.8.1.3
networks:
  wg-easy:
    ipam:
      config:
        - subnet: 10.8.1.0/24`

**Comment by itsMikeLowrey** [comment]
this yaml gives me this error
`# pihole -g
  [✗] DNS resolution is currently unavailable
  [✗] DNS resolution is not available`

**Comment by Pleonazm** [comment]
As a temporary solution maybe instead of using a dedicated VM, just use a Linux container using the Mac-Vlan network. It will be seen as a separate host in your LAN.
It is much easier on your host resources.
