### ISSUE TITLE
Update Requirements for Wireguard Install

### ISSUE THREAD

**Issue by squadramunter** [WeeJeWel/wg-easy#53]
Please update the requirements section on the help page so people don't think Wireguard is included in the docker install. 

This can be confusing since there are wireguard docker containers but these are not included in here.

**Comment by WeeJeWel** [comment]
It does state you need a newer kernel with WireGuard support on the host right?

**Comment by squadramunter** [comment]
Yes, but that does not make sense if Wireguard is also included in this docker container. For beginners it should be better to add a line called: Wireguard needs to be installed or Wireguard not included.

**Comment by WeeJeWel** [comment]
WireGuard is included in the kernel of the host, and the Docker container includes the tools to configure it.

**Comment by squadramunter** [comment]
Yes, exactly. Can you set this above the requirements section? To explain what this is used for? Not that people think this also includes a Wireguard install. There is another person that issued a ticket with restarting in a loop. So your requirements is not clear to everyone.

**Comment by squadramunter** [comment]
As you noted, All in one: Wireguard + WebUI.

This is not correct. This is a WebUI only.

**Comment by WeeJeWel** [comment]
That issue was because the kernel didn't support WireGuard.

**Comment by chibomorto** [comment]
First of all, thanks for the extraordinary work! I know this topic is already closed, but since I'm a noob, do I need to install the Wireguard packages for it to work?
