### ISSUE TITLE
Installation on a remote server

### ISSUE THREAD

**Issue by BotanMan** [WeeJeWel/wg-easy#530]
I have started the container on a remote Ubuntu server, started.

```
docker run -d --name=wg-easy -e WG_HOST=14x.xxx.xxx.xx6 -e PASSWORD=kxxxU  -v ~/.wg-easy:/etc/wireguard  -p 51820:51820/udp  -p 51821:51821/tcp  --cap-add=NET_ADMIN  --cap-add=SYS_MODULE  --sysctl="net.ipv4.conf.all.src_valid_mark=1"  --sysctl="net.ipv4.ip_forward=1"  --restart unless-stopped  weejewel/wg-easy
```

But I can not access the UI

When I try to do
```
curl 0.0.0.0:51821
curl localhost:51821
curl 14x.xxx.xxx.xx6:51821
```

I get the same `Failed to connect to localhost port 51821: Connection refused`

**Expected behavior**
Get text/html response

**Env**
 - Ubuntu
 - Browser 
 - Version 22

**Comment by eandersons** [comment]
Well, you have mapped container's port 51821 to the host's port 80, therefore the user interface is accessible without specifying the port in an address.

**Comment by BotanMan** [comment]
> Well, you have mapped container's port 51821 to the host's port 80, therefore the user interface is accessible without specifying the port in an address.

Sorry, it was a mistake at the example

I did `51821:51821/tcp` in reality.

But both doesn't work 
`localhost` neither `localhost:51821`

I have also opened the port via
`sudo ufw allow 51821` - didn't help

**Comment by eandersons** [comment]
Did you check container logs?
I suspect that the WireGuard Easy container did not start, otherwise the user interface should be reachable with localhost:51821.

**Comment by lowerpower** [comment]
shell into the container and make sure everything is running,:
docker exec -it wg-easy /bin/sh  

/app # netstat -apn
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 :::51821                :::*                    LISTEN      7/node
udp        0      0 0.0.0.0:51820           0.0.0.0:*                           -
udp        0      0 :::51820                :::*                                -
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node PID/Program name    Path

/app # ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:AC:11:00:03  
          inet addr:172.17.0.3  Bcast:172.17.255.255  Mask:255.255.0.0
          inet6 addr: fe80::42:acff:fe11:3/64 Scope:Link
          inet6 addr: fd00:dead:beef:c0:0:242:ac11:3/80 Scope:Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3633198 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5945001 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:4698558064 (4.3 GiB)  TX bytes:4909954586 (4.5 GiB)
...

exit out

then in my example above:
curl 172.17.0.3:51821

if that works, then it is a  mapping issue,  if you can't get the above you got basic docker issues that are not related to this package.
