### ISSUE TITLE
Can't use KDE Connect

### ISSUE THREAD

**Issue by trmdi** [WeeJeWel/wg-easy#533]
When using wg on the host directly, I can use KDE Connect normally.
But when using wg-easy, KDE Connect apps can't find each other.
Some info about the app: https://userbase.kde.org/KDEConnect#I_have_two_devices_running_KDE_Connect_on_the_same_network,_but_they_can't_see_each_other

**Comment by eandersons** [comment]
Just recently I found out a solution for cases when both computer and mobile phone has a connection to the same WireGuard Easy instance and both peers have `0.0.0.0/0` as the allowed IPs - just manually add peer's (computer's) IP address in the WireGuard network (for example, in my case it is 10.0.0.4) in the KDE Connect mobile application (Settings -> Add devices by IP), then the mobile app will "see" the computer.

I you are not using WireGuard on both devices, you could try to exclude the local network addresses - in the [WireGuard `AllowedIPs` Calculator](https://www.procustodibus.com/blog/2021/03/wireguard-allowedips-calculator/) enter `0.0.0.0/0` in the field "Allowed IPs" and `192.168.0.0/16` in the field "Disallowed IPs" (if necessary, adjust both values to your specific needs) and replace peer's `AllowedIPs` with the calculated value. Disclaimer: I did not test this approach.
It is advisable to read the same article's section [A Better Alternative](https://www.procustodibus.com/blog/2021/03/wireguard-allowedips-calculator/#a-better-alternative) as information there might be useful for cases for cases when a (Linux) computer is the device that is using WireGuard.

**Comment by trmdi** [comment]
I've just relized that my phone somehow is blocking its 1716/TCP, which does not happen when disabling wg-easy. How can I unblock it?
