### ISSUE TITLE
Edit Config file to route through alternative interface

### ISSUE THREAD

**Issue by marquiskissel** [WeeJeWel/wg-easy#534]
Hey guys, I have been using this on my synology via docker for a few months. I can't figure out how to update the config to route traffic through my PPTP interface PPP200 instead of eth0. The config file gets overwritten if I change it directly (as warned in the config itself). So how do I change the IPTables entry? Even better would be a way to have it route through PPP200 only when it was available and failover to eth0 when not? I really only need this to do this for one user, so maybe there is a way to do this through the client's config? Would really appreciate the help! Love this community.

**Comment by eandersons** [comment]
You could try to use the environment variable [`WG_POST_UP`](/WeeJeWel/wg-easy#options) (or maybe `WG_PRE_UP`) to apply custom iptables rules.
