### ISSUE TITLE
Does not work if port is changed

### ISSUE THREAD

**Issue by sufd4** [WeeJeWel/wg-easy#54]
I've found that if I change the port to anything but the default 51820 I can no longer connect. The log will just show 
$ wg show wg0 dump

- WG_PORT=21820       is set and docker ports changed to match. allowed in ufw and did port forwarding but no luck. It only will work with default. Any thoughts?

**Comment by jieuryli** [comment]
You wrote that your docker ports were changed to match. Just to make sure, you did this:
```
ports:
  - "21820:51820/udp"
```
Correct?

If so, maybe it's something with your firewall (ufw) rules? I have this running on an alternate port and it works fine.

**Comment by sufd4** [comment]
> You wrote that your docker ports were changed to match. Just to make sure, you did this:
> 
> ```
> ports:
>   - "21820:51820/udp"
> ```
> 
> Correct?
> 
> If so, maybe it's something with your firewall (ufw) rules? I have this running on an alternate port and it works fine.

Perhaps I'm doing this wrong. If you set - WG_PORT=21820 would you not set the ports to 

ports:
      - "21820:21820/udp"

not   - "21820:51820/udp" ? I assumed if you don't change the WG_PORT then the certificates and QR codes would still be set to 51820 incorrectly.

**Comment by jieuryli** [comment]
In the Docker container, WireGuard runs on port 51820/UDP. You need to do this:
```
ports:
  - "21820:51820/udp"
```
to map the "external" port 21820 to the "internal" Dockerized port 51820.

Try this and it should work.

**Comment by jieuryli** [comment]
To be a little more clear, the WG_PORT environment variable is used for client configuration files. When you set WG_PORT=21820 and you download a client configuration file, the Endpoint setting in the [Peer] section looks like this (let's say WG_HOST is set to "example.com"):
```
Endpoint = example.com:21820
```
When you launch your WireGuard client and connect, it connects to example.com at port 21820. Docker (running on the server) will forward that 21820 traffic to the container as port 51820.

To the outside world (configuration file/QR code) the port is 21820, but inside the container it's 51820.

The developer of wg-easy also runs the web server on TCP port 51821 inside the container, but you can change that to any port you want. Like, if you want to access the web UI at port 50080 (e.g. http://example.com:50080), you would do this in the docker-compose.yml file:
```
ports:
  - "21820:51820/udp"
  - "50080:51821/tcp"
```

**Comment by sufd4** [comment]
> To be a little more clear, the WG_PORT environment variable is used for client configuration files. When you set WG_PORT=21820 and you download a client configuration file, the Endpoint setting in the [Peer] section looks like this (let's say WG_HOST is set to "example.com"):
> 
> ```
> Endpoint = example.com:21820
> ```
> 
> When you launch your WireGuard client and connect, it connects to example.com at port 21820. Docker (running on the server) will forward that 21820 traffic to the container as port 51820.
> 
> To the outside world (configuration file/QR code) the port is 21820, but inside the container it's 51820.
> 
> The developer of wg-easy also runs the web server on TCP port 51821 inside the container, but you can change that to any port you want. Like, if you want to access the web UI at port 50080 (e.g. http://example.com:50080), you would do this in the docker-compose.yml file:
> 
> ```
> ports:
>   - "21820:51820/udp"
>   - "50080:51821/tcp"
> ```

Thank you very much for that detailed explanation. My misunderstanding came from thinking that changing WG_PORT changes the port internally that WireGuard runs on as well, not just the config output. Works great now
