### ISSUE TITLE
Daily Docker Build necessary?

### ISSUE THREAD

**Issue by FuzzyMistborn** [WeeJeWel/wg-easy#56]
Just curious why the repo is set to build an image daily?  I run DIUN to notify me of container updates and so I get notifications daily to upgrade the container, but from looking at the dockerfile I don't see why a daily build is needed?  Would it be possible to:

1) reduce the build frequency to weekly?
2) create a "stable" tag that isn't updated as frequently and have the daily builds tagged as "daily" or something like that?
3) build on commits being made?

**Comment by WeeJeWel** [comment]
We update daily to ensure the 'FROM' is always latest.

Additionally, when changes are made, a version is changed and users will see an 'There's an update available' in the UI.

**Comment by FuzzyMistborn** [comment]
So no chance of different tags? It looks like both the latest and 2 tags are updated regularly. I don't always check the UI so that's why I run DIUN to notify me when docker hub sees a new container.

**Comment by WeeJeWel** [comment]
Well, technically speaking it _is_ updated :) But no, I think this is a fine way to ensure latest is always up to date, without maintenance required from me.

**Comment by FuzzyMistborn** [comment]
Respectfully, it's your project so your call, but I highly doubt the "FROM" is updated daily, so seems like a complete waste to build it daily.  I think there's a better solution, but again your call.  Guess I'll look elsewhere for a solution.

**Comment by WeeJeWel** [comment]
A waste of what?

**Comment by FuzzyMistborn** [comment]
Resources from GitHub/Docker. I know it's all free and the builds take only minutes but there has to be a more efficient way that the club of just building everyday. 

Also...it's Wireguard. It doesn't really need to live on the bleeding edge. Security patches sure but again building weekly would likely be fine. Plus looking at the Alpine build history looks like there was an update 2 days ago and then 23 days ago.  Again, just seems like a waste of time to build every day.

**Comment by WeeJeWel** [comment]
It's more a waste of time for me to monitor when some dependency has been updated :) But thanks!

**Comment by FuzzyMistborn** [comment]
Why not look into something like [Dependabot](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates) to monitor when the Alpine image is updated and auto create a new PR (and you can even set it to automerge).  That way your image is only updated when Alpine is updated (or if you manually trigger it).

**Comment by rahilarious** [comment]
> Why not look into something like [Dependabot](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates) to monitor when the Alpine image is updated and auto create a new PR (and you can even set it to automerge). That way your image is only updated when Alpine is updated (or if you manually trigger it).

+1. This sounds like a good idea. When automating anything, flow should be set in most efficient way possible.

**Comment by WeeJeWel** [comment]
There's a nightly being built every day: https://github.com/WeeJeWel/wg-easy/actions/workflows/deploy-nightly.yml
