### ISSUE TITLE
Split the UI as a separate image

### ISSUE THREAD

**Issue by Haarolean** [WeeJeWel/wg-easy#6]
Hi, 

considering a few points:
1) docker containers are designed to run a single process within
2) and end-user of your image could already have wg installed/running

could you please compose an image just with the UI part? 

I have a wg container already running and just want the UI :) Would be nice just to pull the image without forking the repo

**Comment by WeeJeWel** [comment]
It's not as easy, because the Web UI reloads the WireGuard config, for example.

But feel free to fork it yourself.
