### ISSUE TITLE
Error saying Max no of clients reached after adding only 1 user

### ISSUE THREAD

**Issue by c-harsha** [WeeJeWel/wg-easy#62]
Hi, First of all, thanks for making WG-Easy. It has taken out a lot of work on WG Management.

I have created a modified version of **WIREHOLE** using pihole,unbound and WG-Easy. It is working flawlessly during my testing with a single user. I am still using it as I type.

However I am currently facing an issue where I am getting an error message - _Maximum number of clients reached_  whenever I try to add more clients.

![Screenshot 2021-09-01 183155](https://user-images.githubusercontent.com/73026966/131677677-3f3cc717-fee0-4666-934f-afc779f89d62.png)

### Docker-Compose File - ### 

	version: "3.5"

	networks:
	  private_network:
		ipam:
		  driver: default
		  config:
			- subnet: 10.2.0.0/24

	services:
	  unbound:
		image: "klutchell/unbound"
		container_name: unbound
		restart: unless-stopped
		hostname: "unbound"
		ports:
		  - "5053:5053/udp"
		networks:
		  private_network:
			ipv4_address: 10.2.0.200

	  wireguard:
		depends_on: [unbound, pihole]
		image: weejewel/wg-easy
		hostname: "wg-easy"
		container_name: wg-easy
		cap_add:
		  - NET_ADMIN
		  - SYS_MODULE
		environment:
		  # ⚠️ Required:
		  # Change this to your host's public address
		  - WG_HOST=wg.example.com

		  # Optional:
		  - PASSWORD=somepassword
		  - WG_PORT=51820
		  - WG_DEFAULT_ADDRESS=10.6.0.1
		  - WG_DEFAULT_DNS=10.2.0.100 # Set it to point to pihole
		  # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
		volumes:
		  - /lib/modules:/lib/modules
		  - .:/etc/wireguard
		ports:
		  - "51820:51820/udp"
		  - "51821:51821/tcp"
		dns:
		  - 10.2.0.100 # Points to pihole
		  - 10.2.0.200#5053 # Points to unbound
		sysctls:
		  - net.ipv4.conf.all.src_valid_mark=1
		  - net.ipv4.ip_forward=1
		restart: unless-stopped
		networks:
		  private_network:
			ipv4_address: "10.2.0.3"

	  pihole:
		depends_on: [unbound]
		container_name: pihole
		image: jacklul/pihole:latest
		restart: unless-stopped
		hostname: pihole
		dns:
		  - 127.0.0.1
		  - 10.2.0.200#5053 # Points to unbound
		environment:
		  TZ: "America/NewYork"
		  WEBPASSWORD: "" # Blank password - Can be whatever you want.
		  ServerIP: "10.1.0.100" # Internal IP of pihole
		  DNS1: 10.2.0.200#5053 # Unbound IP
		  DNS2: 10.2.0.200#5053 # If we don't specify two, it will auto pick google.
		# Volumes store your data between container upgrades
		volumes:
		  - "./etc-pihole/:/etc/pihole/"
		  - "./etc-dnsmasq.d/:/etc/dnsmasq.d/"
		  - "./etc-pihole-updatelists/:/etc/pihole-updatelists/"
		# Recommended but not required (DHCP needs NET_ADMIN)
		#   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
		cap_add:
		  - NET_ADMIN
		networks:
		  private_network:
			ipv4_address: "10.2.0.100"

**Comment by breadwine** [comment]
I think this line " - WG_DEFAULT_ADDRESS=10.6.0.1" according to readme is for clients ip range.

**Comment by c-harsha** [comment]
Thanks. That did the trick.
