### ISSUE TITLE
Update readme.md - add volume for persistent data

### ISSUE THREAD

**Issue by WillemWever** [WeeJeWel/wg-easy#75]
Hi, would you like to update the readme with volume information. I think that users should mount /etc/wireguard to a local folder (on the host) to persistent changes in the config.

**Comment by cb3inco** [comment]
@WillemWever doesn't is put the contents of /etc/wireguard in to the same folder that the docker-compose file is in? That's the way the docker-compose file is written .:/etc/wireguard

If you want these somewhere else you would just do:

/folder/path/goes/here:/etc/wireguard

**Comment by WeeJeWel** [comment]
What @cb3inco said :)
