### ISSUE TITLE
WG_PORT not updating vpn port

### ISSUE THREAD

**Issue by smshr** [WeeJeWel/wg-easy#9]
I set the environment variable WG_PROT to `443` in kubernetes deployment.yml
```
  env:
  - name: WG_PORT
    value: "443"
```

however running `wg show` from within the pod shows that wireguard is still listening to port 51820, see the output below:

```
➜ nas-kubernetes-cluster git:(master) ✗ kubectl -n apps exec --stdin --tty deployment/wireguard -- /bin/bash
bash-5.0# wg show
interface: wg0
  public key: 53Cxxx=
  private key: (hidden)
  listening port: 51820

peer: DSGxxx=
  preshared key: (hidden)
  allowed ips: 10.0.0.2/32

```

needless to say that I am still trying to make it work in kubernetes.

**Comment by WeeJeWel** [comment]
WireGuard always runs on port 51820. `WG_PORT` is your _public_ port, if you have mapped it from Docker.

**Comment by smshr** [comment]
Oh! I see. `WG_HOST` and `WG_PORT` are only required to generate config for clients to connect. Since clients need public ip/dns and port, these two variables need to be passed to the application.
Is this correct?

**Comment by WeeJeWel** [comment]
Yes!
