### ISSUE TITLE
Custom MTU

### ISSUE THREAD

**Issue by DerDanilo** [WeeJeWel/wg-easy#95]
I am missing an option to define a custom MTU which is required in some cases. It needs to be defined on the server side and written into the client profiles as well. 

Since some ideas were rejected I wanted to ask if a merge request providing this setting will be accepted before investing time.

I intend to make it optional of course and stick to the WG default value as default (for the README).

Thanks!

**Comment by rsheasby** [comment]
Also would love to see this. Just discovered my setup requires a lowered MTU, and had to manually edit config files to add `MTU = 1370`. Hoping to deploy to more devices and want to avoid needing to edit every file manually.

**Comment by WeeJeWel** [comment]
Fixed. Now the `WG_MTU` environment variable is available in v5.

[Consider donating! 🍻](https://github.com/sponsors/WeeJeWel)
