### ISSUE TITLE
Port Forwarding

### ISSUE THREAD

**Issue by Neptunespace** [WeeJeWel/wg-easy#97]
Hello dev ;)

Your container is insane, really, simple, good ui, work amazing but just one thing can be awesome : port forwarding :)

A simple exemple > i run qbittorrent on another server, my qbittorrent is connect to wireguard and i wan't to access to them with the IP of the server where is your container wireguard run :)

==============...................................................................===================================
Server 1....................................................................................Server 2

wg-esay container     <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<     qbittorrent run inside my client wireguard
ipv4 : 12.12.12.12......................................................................ipv4 : 24.24.24.24
==============...................................................................===================================

....... is space blank space

This sublim schema XD

Now :
For connect to my qbitt
Start vpn on my pc to connect to wg-esay container
type the ip adress + the port (8080 for qbittorrent) of the server 2 connections in my case (10.8.0.13:8080) :
![image](https://user-images.githubusercontent.com/93327314/139332826-62ecb2e7-f4cf-4d32-a3d7-cdc3aba6e067.png)

The connection when you are connected to the vpn but without nop :(

And now in my dream :
i just type the ipv4 : 12.12.12.12:8080 and boom qbittorrent is here :)
I have tried to map the port 8080 on the container to make the traffic go out on my IPv4 12.12.12.12 but nop the vpn don't do the forwarding inside the container and in this case i can't make the traffic go out :)

I think it's just a small settings in wireguard we need to activate :)

Wait for you reply 🙏🏻

**Comment by polhaghverdian** [comment]
If you are using docker-compose you can add  below: which will give you access to local services running on the host by connecting to host.docker.internal 

extra_hosts:
      - "host.docker.internal:host-gateway"

**Comment by Neptunespace** [comment]
> If you are using docker-compose you can add below: which will give you access to local services running on the host by connecting to host.docker.internal
> 
> extra_hosts: - "host.docker.internal:host-gateway"

Hello men, thx for trying to help me but nop, not working :(


Wireguard runs an independent private network, only if you are connected to the independent network of the vpn then you can see qbittorent or the other apps that are connected in it, docker can't do anything about it :( Only code can do that :(

**Comment by WeeJeWel** [comment]
Please move this to a discussion.
